CHANGELOG.md
settings/index.js

 Rely on new-style permission name to guard loan-policy settings

---

package.json

This package is no longer in use, and old versions of it can cause the console warning, `Warning: Accessing PropTypes via the main React package is deprecated...`

removing unused package

---

settings/FixedDueDateScheduleForm.js

When adding a new row with `fields.unshift()` instead of
`fields.push()`, the new row is a clone of the topmost row instead of an
empty row. Huh? See UICIRC-29.
Adding new rows as part of the FieldArray component if the `fields`
pseudo-array is empty causes a console error because those pseudo-array
manipulators (push, pop, shift, unshift) aren't actually mutators, the
issue state changes to the store. So there needs to be an alternative
implementation to achieve that effect. See UICIRC-30.

be less buggy when adding rows. Refs UICIRC-29, UICIRC-30.

---

CHANGELOG.md
settings/FixedDueDateScheduleForm.js

This commit changes "push" to "unshift" and closes a ticket as a result,
but really @JohnC-80  should get the credit for fixing the Datepicker
element so that it behaves nicely under both circumstances. So,
technically this fixes UICIRC-29 but really the work was on STCOM-119.

add emptry schedules rows to top of list. Fixes UICIRC-29

---

settings/FixedDueDateScheduleManager.js

https://issues.folio.org/browse/UICIRC-45
Currently if you create a new fixed due date schedule, it will have two schedules. 
With this PR, only one schedule is shown, and a user can add more if desired.

default to a single fixed due date schedule

---

settings/LoanPolicySettings.js

https://issues.folio.org/browse/UICIRC-43
Currently, when the user creates a new loan policy, there is no validation for the Fixed profile.
With this PR, if the profile is 'Fixed', the form will require fixedDueDateSchedule to be set, too.

validate fixedDueDateSchedule field

---

settings/FixedDueDateScheduleManager.js
settings/LoanPolicySettings.js

https://issues.folio.org/browse/UICIRC-42
Currently, if you create a Fixed Due Date Schedule, then create a new Fixed Loan Policy, you will not see that schedule available. This PR fixed that bug.
Thanks to @MikeTaylor and @zburke for the tip.

add dataKey prop to properly sync data with store

---

settings/FixedDueDateScheduleManager.js
settings/LoanPolicySettings.js
settings/LoanRules.js

https://issues.folio.org/browse/UICIRC-42
This PR fixes the bug that resources were not shared between Settings pages. Now the manifest specifies the dataKey used by the other Settings page, and the resource is a unique name (not `entries`)
Dependencies:
- https://github.com/folio-org/stripes-smart-components/pull/99: parameterize resourceKey for EntryManager
- https://github.com/folio-org/stripes-connect/pull/37 support dataKey in manifest

Share resources between Settings pages

---

package.json
settings/FixedDueDateScheduleForm.js

https://issues.folio.org/browse/STCOM-284
Components previously found in `@folio/stripes-components/lib/structures` are now at `@folio/stripes-components/lib`.

STCOM-284 Update stripes-components paths

---

CHANGELOG.md
package.json

The stripes-components dependency was out of sync with stripes-core,
which was causing funky overlaps of the settings pane where the third
column would be superimposed on the second. This probably means we have
our Pane and Paneset components in the wrong repository, or maybe that
we are managing that dependency incorrectly. In any case, the version of
stripes-components we get from stripes-core needs to be the same as the
one we depend on here. And now it is.

stripes-components dep consistent with stripes-core

---

settings/RequestCancellationReasons.js

We're not using `objectLabel` since we're not using the `numberOfObjects` column.

Settings RCR: Remove unused objectLabel

---

package.json
settings/FixedDueDateScheduleForm.js

Generation of HTML element-IDs in `<ConfirmationModal>` changed in
https://github.com/folio-org/stripes-components/commit/ce3ba8c996463a389ae3c3aeb36069d9a785ed69
and that broke a bunch of tests that relied on the old style of element
IDs. Happily, we can restore this behavior by passing in an ID prop that
matches the old format.
Refs [STCOM-317](https://issues.folio.org/browse/STCOM-317)

pass id prop to ConfirmationModal

---

CHANGELOG.md
settings/CheckoutSettings.js
settings/CheckoutSettingsForm.js

Sometimes, the checkboxes for checkout-scanning would not show. I don't
know why, exactly, but it's clear that was not the desired behavior, and
it's clear that when they didn't show, then we couldn't check those
boxes as we wanted to in integration tests, and then those tests would
fail. May the fail no longer.
Refs [UICIRC-75](https://issues.folio.org/browse/UICIRC-75)

always show checkout-scanning checkboxes

---

CHANGELOG.md
settings/RequestCancellationReasons.js

`<ControlledVocab>` now requires the sortby prop.
Refs [STSMACOM-139](https://issues.folio.org/browse/STSMACOM-139)

provide sortby clause to ControlledVocab

---

settings/CheckoutSettings.js
settings/CheckoutSettingsForm.js
settings/FixedDueDateScheduleDetail.js
settings/FixedDueDateScheduleForm.js
settings/FixedDueDateScheduleManager.js
settings/LoanPolicyDetail.js
settings/LoanPolicyForm.js
settings/LoanPolicySettings.js
settings/LoanRules.js
settings/RequestCancellationReasons.js
settings/StaffSlips/PreviewModal.js
settings/StaffSlips/StaffSlipDetail.js
settings/StaffSlips/StaffSlipEditor.js
settings/StaffSlips/StaffSlipForm.js
settings/StaffSlips/StaffSlipManager.js
settings/index.js

Taking into account that retrieving the intl object from this.context.intl or the stripes god object (stripes.intl) is a deprecated pattern.
The purpose of this PR is to update this repo to only use react-intl constructs outlined at https://github.com/folio-org/stripes-core/blob/master/doc/i18n.md
React Intl docs: https://github.com/yahoo/react-intl/wiki

[UICIRC-91] Use documented react-intl patterns instead of stripes.intl

---

CHANGELOG.md
settings/CheckoutSettingsForm.js

Providing `type="checkbox"` to redux-form's `<Field>` kicks it into
boolean mode so it can correctly recognize `value` as a boolean.

provide typehint to Field

---

settings/LoanRules.js

Sometimes, Nightmare tests would blow up with an error like this:
```
Uncaught (in promise) TypeError: Cannot read property 'sendCallout' of null
```
which is the result of the delete method being called before the whole
DOM renders, which causes the callout to fail because it relies on a ref
which isn't available yet because the DOM hasn't rendered. Got that?
Good.

validate callouts before calling them

---

settings/FixedDueDateScheduleForm.js

`clickable-id-set` sure feels like it was copied from a page dealing
with sets of something. No sets here.

use consistent id values

---

CHANGELOG.md
settings/CheckoutSettings.js
settings/CheckoutSettingsForm.js
settings/FixedDueDateScheduleDetail.js
settings/FixedDueDateScheduleForm.js
settings/FixedDueDateScheduleManager.js
settings/LoanPolicyDetail.js
settings/LoanPolicyForm.js
settings/LoanPolicySettings.js
settings/LoanRules.js
settings/RequestCancellationReasons.js
settings/StaffSlips/PreviewModal.js
settings/StaffSlips/StaffSlipDetail.js
settings/StaffSlips/StaffSlipEditor.js
settings/StaffSlips/StaffSlipForm.js
settings/StaffSlips/StaffSlipManager.js
settings/index.js
settings/lib/RuleEditor/LoanRulesEditor.js
settings/lib/RuleEditor/LoanRulesForm.js
settings/lib/RuleEditor/loan-rules-show-hint.js
settings/lib/RuleEditor/loanRules-hint.js
translations/ui-circulation/en.json

Regarding [UICIRC-97](https://issues.folio.org/browse/UICIRC-97), all the hardcoded strings should be internationalized using the react-intl pattern constructs outlined [here](https://github.com/folio-org/stripes/blob/master/doc/i18n.md).
[React Intl docs](https://github.com/yahoo/react-intl/wiki)

UICIRC-97: Apply internationalization to all hardcoded strings

---

settings/FixedDueDateScheduleForm.js
settings/FixedDueDateScheduleManager.js
settings/LoanPolicyForm.js
settings/LoanPolicySettings.js
settings/RequestCancellationReasons.js
settings/StaffSlips/StaffSlipForm.js
settings/index.js
settings/lib/RuleEditor/LoanRulesEditor.js
settings/lib/RuleEditor/LoanRulesForm.js
settings/lib/RuleEditor/loanRules-hint.js

- Same pattern as https://github.com/folio-org/ui-checkout/pull/201
- Related to https://github.com/folio-org/stripes-components/pull/696 and https://github.com/folio-org/stripes-smart-components/pull/331
- Exclusively use `<FormattedMessage>`, `<FormattedDate>`, and `<FormattedTime>` from `react-intl`. 
- Discontinue using `intl.formatMessage()`, `intl.formatDate()`, and `intl.formatTime()`.

UICIRC-91 Replace formatMessage() with FormattedMessage

---

settings/LoanPolicyDetail.js
settings/LoanPolicyForm.js
settings/components/PolicyPropertySetter/PolicyPropertySetter.js

<h1>Opening time offset field behavior fixed</h1>
<h2>Purpose:</h2>
<ul>
<li>Fix current behavior to match the acceptance criteria</li>
</ul>
<h2>Approach</h2>
<ul><li>Code refactoring</li>
<h2>ToDos</h2>
<ul>
<li>Hide Opening time offset field on details pane if the Closed library due date management field value differs from 'Move to the beginning of the next open service point hours'</li>
<li>Set a default units for the Opening time offset field to Hours</li>
<li>Allow only numbers to be set in `PolicyPropertySetter` input field</li>
<li>Add minimum edge to the inputs</li>
</ul>
</ul>
<h2>Bug links</h2>
<a href="https://issues.folio.org/browse/UICIRC-113">https://issues.folio.org/browse/UICIRC-113</>

Opening time offset field visibility fixed on details pane

---

settings/LoanPolicy/LoanPolicyForm.js
settings/LoanPolicy/components/EditSections/RenewalsSection.js
settings/LoanPolicy/components/EditSections/RequestManagementSection.js
settings/LoanPolicy/components/EditSections/index.js
settings/Models/LoanPolicy.js
settings/Validation/FormValidator.js
settings/Validation/LoanPolicy.js
translations/ui-circulation/en.json

According to UICIRC-139 In order for staff to more clearly distinguish between form fields appropriate only to specific and separate Request Types (e.g., Recalls, Holds, Pages) an accordion element should be added to separate the Request Type subsections and associated form fields appropriately.

UICIRC-139

---

package.json
settings/LoanPolicy/LoanPolicySettings.js
settings/Models/LoanPolicy.js
settings/Models/NoticePolicy.js
settings/Models/common/Metadata.js
settings/Models/common/Period.js
settings/Models/common/index.js
settings/NoticePolicy/NoticePolicyDetail.js
settings/NoticePolicy/NoticePolicyForm.js
settings/NoticePolicy/NoticePolicySettings.js
settings/NoticePolicy/index.js
settings/Validation/NoticePolicy.js
settings/index.js
translations/ui-circulation/en.json

Library staff (administrators) need to be able to setup and configure notice policies to define triggering events and conditions and utilize notice templates.  It this story we are going to create a list of notice policies.
https://issues.folio.org/browse/UICIRC-167

UICIRC-167 - Notice policies list

---

settings/FixedDueDateScheduleManager.js
settings/LoanPolicy/LoanPolicySettings.js

The entryLabel prop will later be fed through a component where it must
be a string, not a React element or object. Make it so.
Fixes [UICIRC-134](https://issues.folio.org/browse/UICIRC-134)

pass entryLabel as a string

---

src/constants.js
src/settings/StaffSlips/StaffSlipForm.js
src/settings/StaffSlips/StaffSlipManager.js

This PR adjusts the CRUD permissions for Staff Slips. Both:
- ui-circulation.settings.staff-slips.post
- ui-circulation.settings.staff-slips.delete
don't exist in the system yet but that's ok for now because adding custom slips is not supported yet. 
https://issues.folio.org/browse/UXPROD-1077

Adjust staff slip permissions. Part of UICIRC-194

---

src/settings/LoanPolicy/LoanPolicyForm.js

`<Select>` accepts a `dataOptions` prop that expects to be an array of
key-value pairs with the props `value` and `label`. It was receiving,
instead, an array of `<option>` elements which caused rendered list to
show up as a series of empty `<option />`s. TBH, I'm not sure how this
ever worked.
Refs [STRIPES-602](https://issues.folio.org/browse/STRIPES-602)

correctly format the dataOptions for a Select

---

src/settings/FixedDueDateScheduleManager.js
src/settings/LoanPolicy/LoanPolicySettings.js

While it would be ideal to implement pagination / infinite scroll here, that currently depends on the `EntryManager` component which is due to be refactored already so for now I've increased the maximum number of loan policies / fixed due date schedules returned in the first request to 100 from the default 10.

Increase loan policy limit

---

src/settings/LoanPolicy/LoanPolicyDetail.js
src/settings/LoanPolicy/LoanPolicyForm.js
src/settings/LoanPolicy/components/EditSections/LoansSection/LoansSection.js
src/settings/LoanPolicy/components/EditSections/RenewalsSection/RenewalsSection.js
src/settings/LoanPolicy/utils/normalize.js
test/bigtest/interactors/loan-policy/loan-policy-detail.js
test/bigtest/tests/loan-policy/loan-policy-detail-test.js
translations/ui-circulation/en.json

- Add ability to uncheck selected value for select component.
- Add missed schedule name value on loan policy view screen.
https://issues.folio.org/browse/UICIRC-208

UCIRC-208 - Loan policies: can't un-select due date schedule

---

src/settings/PatronNotices/PatronNoticeForm.js
test/bigtest/interactors/patron-notice/patron-notice-form.js
test/bigtest/tests/patron-notice/patron-notice-edit-test.js
translations/ui-circulation/en.json

To add action menu for edit page of patron notice templates.
To remove delete patron notice template button from the bottom of the page.
https://issues.folio.org/browse/UICIRC-143

UICIRC-143 - added actions menu for patron notice templates edit page.

---

src/settings/NoticePolicy/components/HeaderPane/HeaderPane.js
test/bigtest/interactors/notice-policy/notice-policy-form.js
test/bigtest/tests/notice-policy/notice-policy-edit-test.js

To add an ability to cancel editing mode from actions menu.
https://issues.folio.org/browse/UICIRC-229

UICIRC-229 - Added cancel button to actions menu on notice policy edit page.

---

src/settings/CirculationRules.js

@zburke started seeing issues with integration tests. It looks like the last item in each rule was not correctly converted to UUID. This PR is trying to address it which hopefully makes the tests happy again.

Fix regex for the last item in each rule. Part of UICIRC-210

---

CHANGELOG.md
src/settings/LoanPolicy/components/HeaderPane/HeaderPane.js

It's much easier to write integration tests when page elements have
unique IDs.
Refs [UICIRC-237](https://issues.folio.org/browse/UICIRC-237)

provide IDs for loan-policy's action menu buttons

---

src/settings/index.js

The `isActive` attribute for links in the settings pages was missing,
causing links in the "Circulation" (second pane) section of the settings
pages not to be highlighted when they were active.

restore isActive handler for navigation links

---

src/settings/PatronNotices/PatronNoticeForm.js
src/settings/PatronNotices/PatronNotices.js
src/settings/components/TemplateEditor/TokensModal/TokensModal.js
test/bigtest/interactors/patron-notice/patron-notice-form.js
test/bigtest/tests/patron-notice/patron-notice-delete-test.js
translations/ui-circulation/en.json

- to prohibit user to delete patron notice template if it's currently in use
https://issues.folio.org/browse/UICIRC-185

UICIRC-185 - Not allow user to delete patron notice template if currently in use

---

src/settings/PatronNotices/TokensList/TokensList.js
src/settings/PatronNotices/tokens.js
src/settings/components/TemplateEditor/TokensSection/TokensSection.css
translations/ui-circulation/en.json

Expand location-specific token list for patron notice templates
https://issues.folio.org/browse/UICIRC-250

UICIRC-250 - Expand location-specific token list for patron notice templates

---

src/settings/NoticePolicy/NoticePolicySettings.js

To increase fetch limit for patron notice templates.
https://issues.folio.org/browse/UICIRC-269

UICIRC-269 - New notice template of request type not displaying as an option in policy.

---

CHANGELOG.md
src/settings/lib/RuleEditor/CodeMirrorCustom.css
src/settings/lib/RuleEditor/rules-show-hint.js

Fix display position of autocompletion popup in circulation rules editor in the scope of the [issue](https://issues.folio.org/browse/UICIRC-209)
The hint is displayed for the 17 line.

UICIRC-209: Fix display position of autocompletion popup in circulation rules editor

---

src/settings/components/TemplateEditor/Attributors/indent.js
src/settings/components/TemplateEditor/EditorToolbar/EditorToolbar.js
src/settings/components/TemplateEditor/TemplateEditor.js
src/settings/components/TemplateEditor/quillCustom.css
test/bigtest/interactors/patron-notice/patron-notice-form.js
test/bigtest/tests/patron-notice/patron-notice-editor-test.js

To replace class names to inline styles for template editor content.
https://issues.folio.org/browse/UICIRC-271

UICIRC-271 - Email notice doesn't render in rich text even though it's defined in template

---

CHANGELOG.md
package.json
src/constants.js
src/settings/LoanHistory/ExceptionCard.css
src/settings/LoanHistory/ExceptionCard.js
src/settings/LoanHistory/ExceptionsList.css
src/settings/LoanHistory/ExceptionsList.js
src/settings/LoanHistory/LoanHistory.js
src/settings/LoanHistory/LoanHistoryForm.js
src/settings/Models/LoanHistoryModel.js
src/settings/Validation/engine/FormValidator.js
src/settings/Validation/index.js
src/settings/Validation/loan-history/general.js
src/settings/Validation/loan-history/index.js
src/settings/Validation/loan-history/loan-exceptions.js
src/settings/Validation/loan-history/loan-history.js
src/settings/components/AnonymazingTypeSelect/AnonymazingTypeSelect.js
src/settings/components/AnonymazingTypeSelect/AnonymazingTypeSelectContainer.css
src/settings/components/AnonymazingTypeSelect/AnonymazingTypeSelectContainer.js
src/settings/components/AnonymazingTypeSelect/index.js
src/settings/components/RadioButtons/index.js
src/settings/components/index.js
test/bigtest/interactors/loan-history/loan-history-form.js
test/bigtest/network/factories/payments.js
test/bigtest/network/models/payments.js
test/bigtest/network/scenarios/testLoanHistory.js
test/bigtest/tests/loan-history/loan-history-form-test.js
translations/ui-circulation/en.json

**Purpose**
Create settings in UI for users to anonymize closed loans with fees/fines and exception for payment method according to [story](https://issues.folio.org/browse/UIORG-176).

Loan history settings (anonymize closed loans with fees/fines - exception for payment method)

---

CHANGELOG.md
src/settings/LoanPolicy/LoanPolicySettings.js
src/settings/NoticePolicy/NoticePolicySettings.js
src/settings/PatronNotices/PatronNotices.js
src/settings/RequestPolicy/RequestPolicySettings.js

The default limit for a query is 10. 10 is too small, so now we retrieve
more. More Loan policies, more Patron notice policies, more Patron
notice templates, more Request policies. More is good. More is more.
Often, less is more, but not always, because sometimes most is more.
Refs [UICIRC-302](https://issues.folio.org/browse/UICIRC-302)

UICIRC-302 retrieve more elements in settings

---

CHANGELOG.md
package.json
src/settings/components/TemplateEditor/PreviewModal/PreviewModal.js

`react-to-print` v1 depends directly on React with a caret dep on
version 16. This has the effect of pulling in the most-recent React 16.x
build into any bundle that uses this module, even if that module has a
more strict tilde dep on a less-than-current React minor release.
Whatnow? Say an app depends on React ~16.8.0; React 16.9.0 still gets
into the bundle because of the loose (caret) direct dependency in
react-to-print v1. This was fixed in
https://github.com/gregnb/react-to-print/pull/53 and appears to be the
straw that broke the v1.0-camel's back.
v2 also changed from using a `window` to an `iframe` to handle printing,
but does not automatically clean up the iframe after printing is
finished. This appears to be an oversight, but rather than introduce
another breaking change, they …

UIIN-678 avoid buggy react-to-print version

---

test/bigtest/tests/staff-slip/staff-slip-settings-test.js

Found that without the fix the page is crashed while running the test as the slips were created by not using the factory and contained only ids, however, the tests pass.

Fix staff slip test

---

CHANGELOG.md
src/settings/lib/RuleEditor/CodeMirrorCustom.css
src/settings/lib/RuleEditor/Rules-hint.js
src/settings/lib/RuleEditor/RulesEditor.js
src/settings/lib/RuleEditor/rules-show-hint.js
test/bigtest/interactors/circulation-rules.js
test/bigtest/tests/circulation-rules-test.js

Implement moving to the previous section in current sections list upon click on Backspace button. Implement hint selecting functionality upon mouse click. Refs [UICIRC-285](https://issues.folio.org/browse/UICIRC-285).
- clicking on Backspace button
- clicking on a mouse button

UICIRC-285: Add backward moving feature to organization hierarchy menus in circulation rules editor

---

CHANGELOG.md
src/settings/lib/RuleEditor/CodeMirrorCustom.css
src/settings/lib/RuleEditor/Rules-hint.js
src/settings/lib/RuleEditor/rules-show-hint.js
test/bigtest/interactors/circulation-rules.js
test/bigtest/tests/circulation-rules-test.js
translations/ui-circulation/en.json

Add location items filtering into the circulation rules editor menu in the scope of the [story](https://issues.folio.org/browse/UICIRC-314).

UICIRC-314: Add location items filtering into the circulation rules editor menu

---

src/settings/lib/RuleEditor/rules-show-hint.js

Fix a bug about the incorrect filtered item selection on mouse click. This is an additional change for the [ticket](https://issues.folio.org/browse/UICIRC-314).

UICIRC-314: Fix filtered items selection on mouse click

---

package.json
src/constants.js
translations/ui-circulation/en.json

- add "Item recalled" event to Loans section
- remove "Due date change" event from Requests section
- update patron-notice-policy-storage version
- update event name for "Hold expiration event"
https://issues.folio.org/browse/UICIRC-279

UICIRC-279 -Patron notice policy events updates

---

CHANGELOG.md
src/settings/lib/RuleEditor/Rules-hint.js
src/settings/lib/RuleEditor/RulesEditor.js
src/settings/lib/RuleEditor/rules-show-hint.js
test/bigtest/tests/circulation-rules-test.js

Add handling of the special item Any for intermediate menus and remove the Any item for the last menus in scope of the [story](https://issues.folio.org/browse/UICIRC-334).

UICIRC-334: Add handling of the special item Any for intermediate menus

---

src/settings/components/TemplateEditor/PreviewModal/PreviewModal.js
src/settings/components/TemplateEditor/TemplateEditor.css
src/settings/components/TemplateEditor/TemplateEditor.js
src/settings/components/TemplateEditor/quillCustom.css

- add ability to resize template editor
https://issues.folio.org/browse/UICIRC-295

UICIRC-295 - Allow user to resize text area for notice and staff slip templates

---

CHANGELOG.md
src/settings/CirculationRules.js
src/settings/lib/RuleEditor/rules-show-hint.js
src/settings/utils/location-code-formatters.js
test/bigtest/tests/circulation-rules-test.js

Add full hierarchical path to location codes in the circulation rules editor field in the scope of the [story](https://issues.folio.org/browse/UICIRC-333).

UICIRC-333: Add full hierarchical path to location codes in the circulation rules editor field

---

CHANGELOG.md
src/settings/LoanPolicy/LoanPolicyForm.js
src/settings/LoanPolicy/components/EditSections/RequestManagementSection/RequestManagementSection.js
test/bigtest/tests/loan-policy/loan-policy-form-test.js

The PR makes the loan policy holds section be open by default. It also fixes some minor issues related to `Alternate loan period at renewal for items with an active, pending hold request` field visibility.
https://issues.folio.org/browse/UICIRC-349

Fix loan policy holds section. Refs UICIRC-349

---

CHANGELOG.md
src/settings/LoanHistory/ExceptionsList.js
src/settings/LoanHistory/LoanHistory.js
src/settings/LoanHistory/LoanHistoryForm.js
src/settings/LoanHistory/utils/normalize.js
test/bigtest/interactors/loan-history/loan-history-form.js
test/bigtest/tests/loan-history/loan-history-form-test.js

Clean up Loan history model before sending to the backend according to the [story](https://issues.folio.org/browse/UITEN-57).
**Demo**

UITEN-57: Clean up Loan history model before sending to backend

---

CHANGELOG.md
package.json

`isomorphic-fetch` caused errors in some unit tests and was factored out
of the codebase in #448. This update simply removes the (now unused)
dependency from the `package.json` file.
Refs [UICIRC-355](https://issues.folio.org/browse/UICIRC-355)

UICIRC-355 follow-up: remove isomorphic-fetch

---

CHANGELOG.md
src/constants.js
src/settings/CirculationRules.js
src/settings/lib/RuleEditor/initRulesCMM.js
src/settings/utils/rules-string-convertors.js
test/bigtest/helpers/messageConverters.js
test/bigtest/network/factories/loan-policy.js
test/bigtest/network/factories/patron-notice-policy.js
test/bigtest/network/factories/request-policy.js
test/bigtest/tests/circulation-rules-test.js
test/bigtest/tests/rules-string-convertors-test.js

Fix data replacement issues in the circulation rules editor, that are listed in the description and comments in the [issue](https://issues.folio.org/browse/UICIRC-305) (The issue with reserved keywords (all, m, g, t, a, b, c, s and other) was moved out of the scope).

UICIRC-305: Fix data replacement issues in the circulation rules editor

---

CHANGELOG.md
src/constants.js
src/settings/CirculationRules.js
src/settings/lib/RuleEditor/RulesEditor.js
test/bigtest/network/config.js
test/bigtest/network/factories/overdue-fine-policy.js
test/bigtest/tests/circulation-rules-test.js
translations/ui-circulation/en.json

Add overdue fine policies handling (menu and parsing) to the circulation rules editor in the scope of [UICIRC-353](https://issues.folio.org/browse/UICIRC-353).

UICIRC-353: Add overdue fine policies menu to the circulation rules editor

---

src/settings/LoanPolicy/LoanPolicyDetail.js
src/settings/LoanPolicy/components/ViewSections/RenewalsSection/RenewalsSection.js

To show renewals section in case is policy is loanable
https://issues.folio.org/browse/UICIRC-350

UICIRC-350 - Loan policy: Renewals section not displaying in view when Renewable = N

---

CHANGELOG.md
src/constants.js
src/settings/LoanHistory/LoanHistory.js
src/settings/components/AnonymizingTypeSelect/AnonymizingTypeSelectContainer.js

Add minutes and hours support to the loan history form in the scope of the [issue](https://issues.folio.org/browse/UICIRC-388).

UICIRC-388: Add minutes and hours support to the loan history form

---

CHANGELOG.md
src/settings/PatronNotices/tokens.js

Add requestExpirationDateTime and holdShelfExpirationDateTime tokens for patron notices.
https://issues.folio.org/browse/UICIRC-396

UICIRC-396 - Add hold shelf exp and request exp date/time tokens to patron notice templates

---

src/settings/LoanHistory/LoanHistoryForm.js

Add to PaneFooter's `save` button missing prop `buttonStyle`, to make button blue color, when it is enabled 
---
https://issues.folio.org/browse/UICIRC-375
---

UICIRC-375: Add buttonStyle missing prop

---

CHANGELOG.md
src/settings/LostItemFeePolicy/LostItemFeePolicyForm.js

The wrapper in the lost-item fee-policy form incorrectly contained
accordion-section styling, resulting in the form not expanding to make
use of the full width of the window. This was especially apparent on
narrow windows.

remove extra/incorrect accordion styling

---

src/settings/CheckoutSettingsForm.js

To send checkoutTimeoutDuration as an integer value for checkout settings.
https://issues.folio.org/browse/UICIRC-435

UICIRC-435 - Should use Integer not String for checkout timeout value

---

src/settings/components/TemplateEditor/TemplateEditor.js

Update editor configuration in order to support another block tag. 
https://issues.folio.org/browse/UICIRC-436
**Before**
**After**

UICIRC-436 - Styling of patron notices should support better line spacing

---

CHANGELOG.md
src/settings/NoticePolicy/utils/get-templates.js
test/bigtest/tests/notice-policy/notice-policy-detail-test.js

On New/Edit Patron notice policy page: make Inactive loan and request notice templates **NOT** display in dropdown
https://issues.folio.org/browse/UICIRC-418
**Loan demo (the same with request)**

UICIRC-418: Show in template dropdown only active policies

---

src/settings/NoticePolicy/components/DetailSections/GeneralSection/GeneralSection.js

I noticed some console errors flying by while running integration tests.
Here, optional fields were listed as required; now they are optional and
have sensible defaults. Presto! No more console errors.

props cleanup

---

CHANGELOG.md
package.json

`moment` `v2.25` less than `v2.25.3` caused many webpack-related bugs
([5489](https://github.com/moment/moment/issues/5489), [5472](https://github.com/moment/moment/issues/5472)).
Refs STRIPES-678
Replaces #553

STRIPES-678 avoid moment < 2.25.3

---

src/settings/PatronNotices/tokens.js

Changed preview value for feeCharge.remainingAmount
https://issues.folio.org/browse/UICIRC-458

UICIRC-458 - Extend fee/fine tokens available for notices

---

CHANGELOG.md
src/settings/FixedDueDateScheduleDetail.js

To fix dates displaying on view fixed due date schedules page.
https://issues.folio.org/browse/UICIRC-460

UICIRC-460 - Fixed Due Date Schedule - Dates on Edit/Create and View out of sync

---

CHANGELOG.md
src/settings/FinePolicy/FinePolicyForm.js
src/settings/FinePolicy/FineSection.css
src/settings/FixedDueDateSchedule.css
src/settings/FixedDueDateScheduleForm.js
src/settings/LoanPolicy/LoanPolicyForm.css
src/settings/LoanPolicy/LoanPolicyForm.js
src/settings/LostItemFeePolicy/LostItemFee.css
src/settings/LostItemFeePolicy/LostItemFeePolicyForm.js
src/settings/NoticePolicy/NoticePolicyForm.css
src/settings/NoticePolicy/NoticePolicyForm.js
src/settings/PatronNotices/PatronNoticeForm.css
src/settings/PatronNotices/PatronNoticeForm.js
src/settings/RequestPolicy/RequestPolicyForm.css
src/settings/RequestPolicy/RequestPolicyForm.js
src/settings/StaffSlips/StaffSlipForm.css
src/settings/StaffSlips/StaffSlipForm.js
src/settings/components/FooterPane/FooterPane.js
translations/ui-circulation/en.json

Fix page footer for circulation settings pages.
https://issues.folio.org/browse/UICIRC-469
**Before**
**After**

UICIRC-469 - Incorrect footer displaying for circulation settings

---

src/settings/lib/RuleEditor/CodeMirrorCustom.css

Any indents should not be added to `CodeMirror-scroll` class.  A small padding gave effect that the line is just cut off, and the scrollbal is in the bottom, but in fact it can be scrolled more.
https://issues.folio.org/browse/UICIRC-456

UICIRC-456: Change style

---

src/settings/Validation/engine/handlers.js
src/settings/Validation/fine-policy/fines.js
test/bigtest/tests/fine-policy/fine-policy-form-test.js

Fix incorrect validation behavior for Maximum overdue fine and Maximum recall overdue fine fields.
https://issues.folio.org/browse/UICIRC-476

UICIRC-476 - fixed incorrect validation for overdue fines

---

CHANGELOG.md
src/settings/PatronNotices/TokensList/TokensList.js
src/settings/PatronNotices/tokens.js

- change date related tokens for fee/fine charge and fee/fine actions categories
- disable ability to use loop for fee/fine action tokens
- disable feeCharge.additionalInfo for Automated fee/fine charge or adjustment category
https://issues.folio.org/browse/UICIRC-479

UICIRC-479 - Adjust UI for fee/fine notice token options on templates 

---

src/settings/PatronNotices/tokens.js

Disable loan tokens for manual fee/fine charge category in patron notices
https://issues.folio.org/browse/UICIRC-494

UICIRC-494 - Loan tokens should be unavailable (and greyed out) for manual fee/fine charge category

---

CHANGELOG.md
src/settings/LoanPolicy/LoanPolicyDetail.js
src/settings/LoanPolicy/components/ViewSections/LoansSection/LoansSection.js
test/bigtest/tests/loan-policy/loan-policy-detail-test.js

Display loans section when `loanable` is set to `No`.
https://issues.folio.org/browse/UICIRC-392

UICIRC-392: Display loans section when loanable is set to no

---

src/settings/Validation/loan-policy/loans.js

The work for https://issues.folio.org/browse/UICIRC-392 was done in: https://github.com/folio-org/ui-circulation/pull/622
but the validation was still not working correctly for no loanable items. This PR should fix it.

UICIRC-392: Adjust validation for no loanable policies

---

CHANGELOG.md
src/settings/LostItemFeePolicy/components/EditSections/LostItemFeeSection/LostItemFeeSection.js

In `Lost item fee policy`, when select `Set cost`  and then blank it out (delete the 0.00) -> 
`Lost item fee` displays as `Set cost of NaN`
https://issues.folio.org/browse/UICIRC-500
**Before**
**After**

UICIRC-500: Lost item fee displays as Set cost of NaN

---

CHANGELOG.md
src/settings/Validation/engine/validators.js
src/settings/Validation/lost-item-fee-policy/lost-item-fee.js
translations/ui-circulation/en.json

Remove unnecessary validation for lost item fee policy.
https://issues.folio.org/browse/UICIRC-499

UICIRC-499 - Incorrect error validation for 'Patron billed after aged to lost'

---

src/settings/NoticePolicy/NoticePolicySettings.js
src/settings/PatronNotices/PatronNotices.js

Increase limits for fetching templates (up to 1000)
https://issues.folio.org/browse/UICIRC-518

UICIRC-518 - Validation and other issues with patron notice template names

---

CHANGELOG.md
src/settings/LoanPolicy/components/EditSections/RequestManagementSection/RequestManagementSection.js
src/settings/LoanPolicy/components/ViewSections/RequestManagementSection/RequestManagementSection.js
src/settings/LoanPolicy/utils/normalize.js
src/settings/Models/LoanPolicy/Recalls.js
src/settings/Validation/loan-policy/request-management.js
test/bigtest/interactors/loan-policy/loan-policy-form/request-management-section.js
test/bigtest/tests/loan-policy/loan-policy-form-test.js
translations/ui-circulation/en.json

https://issues.folio.org/browse/UICIRC-525
It was added a new setting on the loan policy (in `Request management` -> `Recalls` section) that allows recalls to extend overdue loans.

UICIRC-525: Add 'Allow recalls to extend overdue loans' setting

---

CHANGELOG.md
src/settings/PatronNotices/PatronNoticeForm.js

Make patron notice template name validation case insensitive.
https://issues.folio.org/browse/UICIRC-528

UICIRC-528 - Duplicate patron notice template names allowed - case is not considered in validation

---

CHANGELOG.md
src/settings/lib/RuleEditor/Rules-hint.js
src/settings/lib/RuleEditor/rules-show-hint.js
src/settings/lib/RuleEditor/utils.js
test/bigtest/tests/circulation-rules-editor/hints-menu/backward-navigation-test.js
test/bigtest/tests/circulation-rules-editor/hints-menu/criteria-hints-menu-test.js

In Circ Rule editor when selecting multiple criteria was a problem with after `Enter` - `rule` with `criteria` were concatenated into regular text. In this PR were added formatted function for adding of `indent` to editor values. Since there were many places where template strings with space used, so I replace them with function too for consistency.
Also add `library` and `campuses` rule multiple selection behavior, because they are - multiple.    
https://issues.folio.org/browse/UICIRC-488
**Before:** https://recordit.co/5lroDBsjUm
**After:** https://recordit.co/0xXdNbmq4v

UICIRC-488: Add space to rule editor to multiple criteria rule

---

src/settings/LoanPolicy/utils/normalize.js

https://issues.folio.org/browse/UICIRC-525
This is an addendum to #659 for normalizing (in this case, clearing) interval data when the checkbox is unchecked.

UICIRC-525: Add clearing interval value when unchecked

---

CHANGELOG.md
src/constants.js
src/settings/PatronNotices/PatronNoticeForm.js
src/settings/PatronNotices/PatronNotices.js
src/settings/PatronNotices/tokens.js
translations/ui-circulation/en.json

- make `fee/fine action` tokens available for `automated fee/fine charge or adjustment` category
- rename `manual fee/fine action` category
- reorder values for `category` dropdown
https://issues.folio.org/browse/UICIRC-537

UICIRC-537 - Add fee/fine action tokens to template with fee/fine charge or adjustment

---

CHANGELOG.md
src/settings/FinePolicy/components/EditSections/OverdueAboutSection/OverdueAboutSection.js
src/settings/LostItemFeePolicy/components/EditSections/LostItemFeeAboutSection/LostItemFeeAboutSection.js
src/settings/NoticePolicy/components/EditSections/GeneralSection/GeneralSection.js
src/settings/PatronNotices/PatronNoticeForm.js
src/settings/RequestPolicy/components/EditSections/GeneralSection/GeneralSection.js
src/settings/StaffSlips/StaffSlipForm.js
test/bigtest/interactors/request-policy/request-policy-form.js
test/bigtest/interactors/staff-slip/staff-slip-form.js
test/bigtest/tests/fine-policy/fine-policy-form-test.js
test/bigtest/tests/lost-item-fee-policy/lost-item-fee-policy-form-test.js
test/bigtest/tests/notice-policy/notice-policy-form-test.js
test/bigtest/tests/patron-notice/patron-notice-form-test.js
test/bigtest/tests/request-policy/request-policy-form-test.js
test/bigtest/tests/staff-slip/staff-slip-form-test.js

First field should be in focus for all forms in circulation settings
https://issues.folio.org/browse/UICIRC-541

UICIRC-541 - First field should be in focus for all forms in circulation settings

---

CHANGELOG.md
package.json

Update `stripes-cli` to `v2.0.0`
https://issues.folio.org/browse/UICIRC-547

UICIRC-547: Update stripes-cli to v2.0.0

---

CHANGELOG.md
src/constants.js
src/settings/FinePolicy/FinePolicySettings.js
src/settings/FixedDueDateSchedule/FixedDueDateScheduleManager.js
src/settings/LoanPolicy/LoanPolicySettings.js
src/settings/LostItemFeePolicy/LostItemFeePolicySettings.js
src/settings/PatronNotices/PatronNotices.js
test/bigtest/tests/fixed-due-date-schedule/fixed-due-date-schedule-validation-test.js

The `limit` was already set to correct value `1000` but it was overwritten by `perRequest`.
This PR removes `perRequest` and replaces `limit` with `maxUnpagedResourceCount` introduced by @MikeTaylor in: https://github.com/folio-org/ui-inventory/pull/1359
`maxUnpagedResourceCount` is set to `1000` by default.
https://issues.folio.org/browse/UICIRC-568

UICIRC-568: Fix limit in policy settings

---

CHANGELOG.md
src/settings/CirculationRules.js

Use larger query limits, and allow an override limit to be specified
when the bundle is built.
Follow up to #723
Refs [UICIRC-568](https://issues.folio.org/browse/UICIRC-568)

UICIRC-568 use larger query limits

---

CHANGELOG.md
package.json

There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.
**Do not merge. We have several associated pull request and we need merge them at the same time.**
**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module
https://issues.folio.org/browse/UICIRC-578

UICIRC-578: Update circulation interface dependency to support v11

---

CHANGELOG.md
translations/ui-circulation/en.json

Fix a typo in the word Year(s) in the Period interval
https://issues.folio.org/browse/UICIRC-662

UICIRC-662: Fix a typo in the word Year(s) in the Period interval

---

CHANGELOG.md
package.json
src/settings/lib/RuleEditor/RulesEditor.js

Update `codemirror` and `react-codemirror2`.
We can update `react-codemirror2` from `1.0.0` to `7.2.1` and `codemirror` from version `5.29.0` (https://github.com/scniro/react-codemirror2/blob/1.0.0/package.json#L35) to `5.61.1`. We have breaking changes in `react-codemirror2` version `3.0.0`. In `react-codemirror2` version `3.0.0` was added `Controlled` and `UnControlled` components instead of `CodeMirror` component (https://github.com/scniro/react-codemirror2/tree/3.0.0). We can easy fix current problem migrate to `Controlled` component and adding `onBeforeChange` (https://github.com/scniro/react-codemirror2#controlled-usage).
https://issues.folio.org/browse/UICIRC-576

UICIRC-576: update `codemirror` and `react-codemirror2`.

---

CHANGELOG.md
package.json

Update folio/stripes-template-editor to 3.0.0
https://issues.folio.org/browse/UICIRC-575

UICIRC-575: Update folio/stripes-template-editor to 3.0.0

---

CHANGELOG.md
src/settings/NoticePolicy/components/DetailSections/FeeFineNoticesSection/FeeFineNoticesSection.js
src/settings/NoticePolicy/components/DetailSections/FeeFineNoticesSection/FeeFineNoticesSection.test.js
test/jest/__mock__/stripesComponents.mock.js

Add RTL/Jest tests for FeeFineNoticesSection component
Test for correct props accept was extracted in separate function for more comfortable check for each part of incoming data
https://issues.folio.org/browse/UICIRC-631

UICIRC-631: add RTL/Jest tests for FeeFineNoticesSection component

---

CHANGELOG.md
src/settings/LoanHistory/utils/normalize.test.js

Add RTL/Jest tests for `normalize` function in `LoanHistory\utils`.
https://issues.folio.org/browse/UICIRC-607

UICIRC-607: add RTL/Jest tests for `normalize` function in `LoanHistory\utils`

---

CHANGELOG.md
src/settings/FinePolicy/components/ViewSections/OverdueAboutSection/OverdueAboutSection.js
src/settings/FinePolicy/components/ViewSections/OverdueAboutSection/OverdueAboutSection.test.js
test/jest/__mock__/stripesComponents.mock.js

Add RTL/Jest tests for `OverdueAboutSection` in `FinePolicy/components/ViewSections`
https://issues.folio.org/browse/UICIRC-598

UICIRC-598: Add RTL/Jest tests for `OverdueAboutSection` in `FinePolicy/components/ViewSections`

---

CHANGELOG.md
src/settings/LostItemFeePolicy/components/ViewSections/LostItemFeeAboutSection/LostItemFeeAboutSection.js
src/settings/LostItemFeePolicy/components/ViewSections/LostItemFeeAboutSection/LostItemFeeAboutSection.test.js

Add RTL/Jest tests for `LostItemFeeAboutSection` component in `LostItemFeePolicy/components/ViewSections`
https://issues.folio.org/browse/UICIRC-625

UICIRC-625: Add RTL/Jest tests for `LostItemFeeAboutSection` component in `LostItemFeePolicy/components/ViewSections`

---

CHANGELOG.md
src/settings/LoanPolicy/components/ViewSections/AboutSection/AboutSection.js
src/settings/LoanPolicy/components/ViewSections/AboutSection/AboutSection.test.js

Add RTL/Jest tests for `AboutSection` in `LoanPolicy/components/ViewSections`
https://issues.folio.org/browse/UICIRC-616

UICIRC-616: Add RTL/Jest tests for `AboutSection` in `LoanPolicy/components/ViewSections`

---

CHANGELOG.md
src/settings/NoticePolicy/utils/get-templates.test.js
src/settings/NoticePolicy/utils/normalize.js
src/settings/NoticePolicy/utils/normalize.test.js
src/settings/NoticePolicy/utils/notice-description.test.js

Add RTL/Jest tests for `utils` in `NoticePolicy`
In `noticeDescription` tests main function for testing was extracted for posibility run tests for each type of events
https://issues.folio.org/browse/UICIRC-642

UICIRC-642: Add RTL/Jest tests for `utils` in `NoticePolicy`

---

CHANGELOG.md
package.json

Support `feesfines` interface version `17.0`
We should merge all associated task with https://issues.folio.org/browse/MODFEE-98 in the same time. In scope of https://issues.folio.org/browse/MODFEE-98 was added the standard UUID regular expression pattern to all the id fields in the Fees/Fines module JSON schemas. All changes was tested in scope https://issues.folio.org/browse/MODFEE-197.
https://issues.folio.org/browse/UICIRC-671
@zburke @mkuklis  Could you please clarify do we need to add someone else for review this task?

UICIRC-671: Support `feesfines` interface version `17.0`

---

CHANGELOG.md
src/settings/NoticePolicy/components/DetailSections/RequestNoticesSection/RequestNoticesSection.js
src/settings/NoticePolicy/components/DetailSections/RequestNoticesSection/RequestNoticesSection.test.js

Add RTL/Jest tests for `RequestNoticesSection` component in `NoticePolicy/components/DetailSections`
https://issues.folio.org/browse/UICIRC-634

UICIRC-634: Add RTL/Jest tests for `RequestNoticesSection` component

---

CHANGELOG.md
src/constants.js
src/settings/utils/rules-string-convertors.js
src/settings/utils/rules-string-convertors.test.js

Add RTL/Jest testing for "rules-string-convertors" in "settings/utils"
https://issues.folio.org/browse/UICIRC-682

UICIRC-682: Add RTL/Jest tests for "rules-string-convertors" in "settings/utils"

---

CHANGELOG.md
src/settings/NoticePolicy/components/DetailSections/GeneralSection/GeneralSection.js
src/settings/NoticePolicy/components/DetailSections/GeneralSection/GeneralSection.test.js

Add RTL/Jest tests for `GeneralSection` component in `NoticePolicy/components/DetailSections`
https://issues.folio.org/browse/UICIRC-632

UICIRC-632: Add RTL/Jest test for `GeneralSection` component

---

CHANGELOG.md
src/settings/components/AnonymizingTypeSelect/AnonymizingTypeSelect.js
src/settings/components/AnonymizingTypeSelect/AnonymizingTypeSelect.test.js
test/jest/__mock__/stripesComponents.mock.js

Add RTL/Jest tests for `AnonymizingTypeSelect` component in `settings/components/AnonymizingTypeSelect`
https://issues.folio.org/browse/UICIRC-653

UICIRC-653: Add RTL/Jest tests for `AnonymizingTypeSelect` component

---

CHANGELOG.md
src/settings/components/AnonymizingTypeSelect/AnonymizingTypeSelect.test.js
src/settings/components/Metadata/Metadata.js
src/settings/components/Metadata/Metadata.test.js
test/jest/__mock__/index.js
test/jest/__mock__/stripesSmartComponents.mock.js

Add RTL/Jest tests for `Metadata` component in `settings/components`
https://issues.folio.org/browse/UICIRC-652

UICIRC-652: Add RTL/Jest tests for `Metadata` component

---

CHANGELOG.md
src/settings/NoticePolicy/components/DetailSections/LoanNoticesSection/LoanNoticesSection.js
src/settings/NoticePolicy/components/DetailSections/LoanNoticesSection/LoanNoticesSection.test.js

Add RTL/Jest tests for `LoanNoticesSection` function in `NoticePolicy/components/DetailSections`
https://issues.folio.org/browse/UICIRC-633

UICIRC-633: Add RTL/Jest tests for `LoanNoticesSection` component in `NoticePolicy/components/DetailSections`

---

CHANGELOG.md
src/settings/NoticePolicy/components/EditSections/LoanNoticesSection/LoanNoticesSection.js
src/settings/NoticePolicy/components/EditSections/LoanNoticesSection/LoanNoticesSection.test.js

Add RTL/Jest tests for `LoanNoticesSection` function in `NoticePolicy/components/EditSections`
https://issues.folio.org/browse/UICIRC-639

UICIRC-639: Add RTL/Jest tests for `LoanNoticesSection` component in `NoticePolicy/components/EditSections`

---

CHANGELOG.md
src/settings/utils/rules-string-convertors.test.js

Add RTL/Jest tests for `convertNamesToIdsInLine` function in `settings/utils/rules-string-convertors.js`
https://issues.folio.org/browse/UICIRC-686

UICIRC-686: Add RTL/Jest tests for `convertNamesToIdsInLine` function in `settings/utils`

---

CHANGELOG.md
Jenkinsfile
package.json
src/settings/LoanPolicy/utils/normalize.test.js
src/settings/utils/location-code-formatters.test.js
src/settings/utils/options-generator.js
src/settings/utils/options-generator.test.js
src/settings/utils/with-dash-replacer.test.js

Add RTL/Jest testing for `location-code-formatters`, `options-generator`, `with-dash-replacer` in `settings/utils`
https://issues.folio.org/browse/UICIRC-656

UICIRC-656: Add RTL/Jest testing for functions in `settings/utils`

---

CHANGELOG.md
src/settings/LostItemFeePolicy/components/EditSections/RadioGroup/RadioGroup.js
src/settings/LostItemFeePolicy/components/EditSections/RadioGroup/RadioGroup.test.js
test/jest/__mock__/stripesComponents.mock.js

Add RTL/Jest tests for `RadioGroup` component in `LostItemFeePolicy/components/EditSections`
https://issues.folio.org/browse/UICIRC-624

UICIRC-624: Add RTL/Jest tests for `RadioGroup` component

---

CHANGELOG.md
src/settings/NoticePolicy/components/EditSections/RequestNoticesSection/RequestNoticesSection.js
src/settings/NoticePolicy/components/EditSections/RequestNoticesSection/RequestNoticesSection.test.js

Add RTL/Jest testing for `RequestNoticesSection` component in `NoticePolicy/components/EditSections`
https://issues.folio.org/browse/UICIRC-640

UICIRC-640: Add RTL/Jest testing for `RequestNoticesSection` component

---

CHANGELOG.md
src/settings/lib/RuleEditor/CodeMirrorCustom.css

The CSS rules governing the line-height of a single location-item are
completely impenetrable to me, but removing the `height` attribute on
the container element somehow, mysteriously, fixes the display. It
appears that what's happening is a bunch of block-level elements with a
too-short line-height are stacked, such that the line below clips that
above, but I couldn't figure out how to change the line-height for a
single element anywhere.
Refs [UICIRC-430](https://issues.folio.org/browse/UICIRC-430)

UICIRC-430 improve location display in circ rules

---

CHANGELOG.md
src/settings/NoticePolicy/components/EditSections/GeneralSection/GeneralSection.js
src/settings/NoticePolicy/components/EditSections/GeneralSection/GeneralSection.test.js

Add RTL/Jest testing for `GeneralSection` component in `NoticePolicy/components/EditSections`
https://issues.folio.org/browse/UICIRC-638

UICIRC-638: Add RTL/Jest tests for `GeneralSection` component

---

CHANGELOG.md
src/settings/RequestPolicy/components/EditSections/GeneralSection/GeneralSection.js
src/settings/RequestPolicy/components/EditSections/GeneralSection/GeneralSection.test.js

Add RTL/Jest testing for `GeneralSection` component in `RequestPolicy/components/EditSections`
https://issues.folio.org/browse/UICIRC-648

UICIRC-648: Add RTL/Jest tests for `GeneralSection` component

---

CHANGELOG.md
src/settings/LoanPolicy/components/ViewSections/RenewalsSection/RenewalsSection.js
src/settings/LoanPolicy/components/ViewSections/RenewalsSection/RenewalsSection.test.js

Add RTL/Jest testing for `RenewalsSection` component in `LoanPolicy/components/ViewSections`
https://issues.folio.org/browse/UICIRC-695

UICIRC-695: Add RTL/Jest tests for `RenewalsSection` component

---

CHANGELOG.md
src/settings/CirculationRules.js

Locations are displayed as `{code} {name}` and thus should be sorted in
the circulation rules editor sorted in that order. Previously, they were
sorted by `name`, which made navigating the list very confusing.
Refs [UICIRC-703](https://issues.folio.org/browse/UICIRC-703), [UICIRC-430](https://issues.folio.org/browse/UICIRC-430)

UICIRC-703 sort locations by code, name

---

translations/ui-circulation/en.json

Fix wording mistake in description of modal.
Main changes for [UICIRC-708](https://issues.folio.org/browse/UICIRC-708) was described in https://github.com/folio-org/ui-circulation/pull/814
https://issues.folio.org/browse/UICIRC-708

UICIRC-708: change modal description wording

---

CHANGELOG.md
src/constants.js
src/settings/NoticePolicy/NoticePolicySettings.js
src/settings/PatronNotices/PatronNotices.js
src/settings/RequestPolicy/RequestPolicySettings.js

We should use constants instead of hardcoded value for query limits.
I invetigated this problem a little bit deeper, and I found that:
- `params.limit` can use only `string` value (app fails if we change it to `number`);
- `recordsRequired` and `perRequest` handle what they got and parse `string` to `number` if need it (found this in `stripes-connect` code);
- in connection with all of the above this code looks a little bit worried for me
It's not make any problems yet, but there are a lot of places where we use such construction. In my opinion it can break the app, if `stripes` will not pass the `maxUnpagedResourceCount` by any reason.
That's the reasons why I changed `MAX_UNPAGED_RESOURCE_COUNT` from number to string. On my opinion this is the universal type for existing code. …

UICIRC-724:  use constants instead of hardcoded value for query limits

---

CHANGELOG.md
package.json
src/index.js
translations/ui-circulation/en.json

Provide a new permission set that grants read-only access to loan
policies, similar to those for overdue fines policies and lost item fees
policies.
Refs [UICIRC-693](https://issues.folio.org/browse/UICIRC-693)

UICIRC-693 provide read-only access to loan policies

---

CHANGELOG.md
src/settings/LoanHistory/ExceptionCard.js
src/settings/LoanHistory/ExceptionCard.test.js

Add RTL/Jest testing for `ExceptionCard` component in `settings/LoanHistory/ExceptionCard`.
https://issues.folio.org/browse/UICIRC-604

UICIRC-604: Add RTL/Jest tests for `ExceptionCard`

---

CHANGELOG.md
src/settings/RequestPolicy/RequestPolicyDetail.js
src/settings/RequestPolicy/RequestPolicyDetail.test.js
test/jest/__mock__/stripesComponents.mock.js

Add RTL/Jest testing for `RequestPolicyDetail` component in `src\settings\RequestPolicy`
https://issues.folio.org/browse/UICIRC-646

UICIRC-646: Add RTL/Jest tests for `RequestPolicyDetail` component

---

CHANGELOG.md
src/settings/PatronNotices/PatronNoticeDetail.js
src/settings/PatronNotices/PatronNoticeForm.js
src/settings/PatronNotices/TokensList/TokensList.test.js
src/settings/PatronNotices/tokens.js
src/settings/PatronNotices/tokens.test.js
src/settings/PatronNotices/utils/constantsForMoment.js
src/settings/PatronNotices/utils/index.js
src/settings/PatronNotices/utils/preview.js
src/settings/PatronNotices/utils/preview.test.js
src/settings/PatronNotices/utils/template.js
test/jest/__mock__/intl.mock.js

UI fee/fine date/time token previews are hard-coded.
Now we set preview values depends on tenant locale. This locale we get from `intl.locale`.
Below I attached two screenshots for different locales. 
https://issues.folio.org/browse/UICIRC-480
For en-US locale:
For en-GB locale:

UICIRC-480: UI fee/fine date/time token previews are hard-coded

---

CHANGELOG.md
src/settings/CheckoutSettings/CheckoutSettings.js
src/settings/CheckoutSettings/CheckoutSettings.test.js
test/jest/__mock__/stripesCore.mock.js

Add RTL/Jest testing for `CheckoutSettings` component in `src/settings/CheckoutSettings`.
https://issues.folio.org/browse/UICIRC-592

UICIRC-592: Add Jest/RTL tests for `CheckoutSettings` component

---

CHANGELOG.md
src/settings/NoticePolicy/NoticePolicyDetail.js
src/settings/NoticePolicy/NoticePolicyDetail.test.js

Add RTL/Jest testing for `NoticePolicyDetail` component in `src/settings/NoticePolicy`
https://issues.folio.org/browse/UICIRC-629

UICIRC-629: Add Jest/RTL tests for `NoticePolicyDetail` component

---

CHANGELOG.md
src/settings/LostItemFeePolicy/LostItemFeePolicyForm.js
src/settings/LostItemFeePolicy/LostItemFeePolicyForm.test.js

Add RTL/Jest testing for `LostItemFeePolicyForm` component in `src/settings/LostItemFeePolicy`.
https://issues.folio.org/browse/UICIRC-619

UICIRC-619: Add Jest/RTL tests for `LostItemFeePolicyForm` component

---

CHANGELOG.md
src/settings/NoticePolicy/NoticePolicyForm.js
src/settings/NoticePolicy/NoticePolicyForm.test.js

Add RTL/Jest testing for `NoticePolicyForm` component in `src/settings/NoticePolicy`.
https://issues.folio.org/browse/UICIRC-630

UICIRC-630: Add Jest/RTL tests for `NoticePolicyForm` component

---

CHANGELOG.md
src/settings/FinePolicy/FinePolicyForm.js
src/settings/FinePolicy/FinePolicyForm.test.js

Add RTL/Jest testing for `FinePolicyForm` component in `src/settings/FinePolicy`.
https://issues.folio.org/browse/UICIRC-737

UICIRC-737: Add Jest/RTL tests for `FinePolicyForm` component

---

CHANGELOG.md
src/settings/LoanPolicy/LoanPolicyForm.js
src/settings/LoanPolicy/LoanPolicyForm.test.js

Add RTL/Jest testing for `LoanPolicyForm` component in `src/settings/LoanPolicy`.
https://issues.folio.org/browse/UICIRC-611

UICIRC-611: Add Jest/RTL tests for `LoanPolicyForm` component

---

CHANGELOG.md
package.json

Support okapi interfaces `circulation` `13.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* Was changed API associated with request queue.
https://issues.folio.org/browse/UICIRC-732

UICIRC-732: Also support circulation 13.0

---

translations/ui-circulation/en.json

UIU-1994 Change setting name for 'If lost item returned, remove lost item processing fee' in Lost Item Fee Policy
https://issues.folio.org/browse/UIU-1994
Replaces #851

UICIRC-752 adjust Lost Item Fee Policy setting name

---

CHANGELOG.md
src/settings/LostItemFeePolicy/LostItemFeePolicyDetail.js
src/settings/LostItemFeePolicy/LostItemFeePolicyDetail.test.js

Add RTL/Jest testing for `LostItemFeePolicyDetail` component in `src\settings\LostItemFeePolicy`.
https://issues.folio.org/browse/UICIRC-621

UICIRC-621: Add Jest/RTL tests for `LostItemFeePolicyDetail` component

---

CHANGELOG.md
package.json

Permission errors with `ui-circulation.settings.loan-history`
https://issues.folio.org/browse/UICIRC-748

UICIRC-748: Permission errors with ui-circulation.settings.loan-history

---

CHANGELOG.md
package.json

Add `circulation.loans.collection.get` as subpermission for `ui-circulation.settings.view-lost-item-fees-policies`.
https://issues.folio.org/browse/UICIRC-745

UICIRC-745: Add `circulation.loans.collection.get` as subpermisson

---

CHANGELOG.md
package.json

Add `circulation.loans.collection.get` as subpermission for `ui-circulation.settings.view-overdue-fines-policies`.
https://issues.folio.org/browse/UICIRC-746

UICIRC-746: Add `circulation.loans.collection.get` subpermisson

---

CHANGELOG.md
package.json

Add `user-settings.custom-fields.collection.get` as subpermission for `ui-circulation.settings.other-settings`
https://issues.folio.org/browse/UICIRC-750

UICIRC-750: Add `user-settings.custom-fields.collection.get` as subpermission

---

CHANGELOG.md
package.json

Add `overdue-fines-policies.collection.get` and `lost-item-fees-policies.collection.get` as subpermissions for `ui-circulation.settings.circulation-rules`.
https://issues.folio.org/browse/UICIRC-714

UICIRC-714: Fix problem with `ui-circulation.settings.circulation-rules` permission

---

CHANGELOG.md
src/settings/LostItemFeePolicy/LostItemFeePolicySettings.js
src/settings/LostItemFeePolicy/LostItemFeePolicySettings.test.js

Add RTL/Jest testing for `LostItemFeePolicySettings` component in `settings/LostItemFeePolicy`.
https://issues.folio.org/browse/UICIRC-758

UICIRC-758: Add Jest/RTL tests for `LostItemFeePolicySettings` component

---

CHANGELOG.md
src/settings/PatronNotices/PatronNotices.js
src/settings/PatronNotices/PatronNotices.test.js

Add RTL/Jest testing for `PatronNotices` component in `settings/PatronNotices`.
https://issues.folio.org/browse/UICIRC-760

UICIRC-760: Add Jest/RTL tests for `PatronNotices` component

---

CHANGELOG.md
src/settings/NoticePolicy/NoticePolicySettings.js
src/settings/NoticePolicy/NoticePolicySettings.test.js

Add RTL/Jest testing for `NoticePolicySettings` component in `settings/NoticePolicy`.
https://issues.folio.org/browse/UICIRC-759

UICIRC-759: Add Jest/RTL tests for `NoticePolicySettings` component

---

CHANGELOG.md
src/settings/RequestPolicy/RequestPolicyForm.js
src/settings/RequestPolicy/RequestPolicyForm.test.js

Add RTL/Jest testing for `RequestPolicyForm` component in `src/settings/RequestPolicy`.
https://issues.folio.org/browse/UICIRC-647

UICIRC-647: Add Jest/RTL tests for `RequestPolicyForm` component

---

CHANGELOG.md
src/index.js

For Lotus release was decided to cut out possibility of TLR settings changing.
https://issues.folio.org/browse/UICIRC-777

UICIRC-777: hide title level requests settings

---

CHANGELOG.md
src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.js
src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.test.js
test/jest/__mock__/finalFormComponents.mock.js
test/jest/helpers/index.js
test/jest/helpers/utils.js

Add RTL/Jest testing for `NoticeCard` component in `src\settings\NoticePolicy\components\EditSections\components`.
https://issues.folio.org/browse/UICIRC-636

UICIRC-636: Add Jest/RTL tests for `NoticeCard` component

---

CHANGELOG.md
src/settings/lib/RuleEditor/RulesEditor.css
src/settings/lib/RuleEditor/RulesForm.js

Cypress issue with **circulation rules form**. When we are trying to interact with form it jumps and cover "save" button.
**DOM** element with class `codeMirrorFullScreen` which contains **circulation rules form** has `position: absolute;` style.  And row which contains this **DOM** element must have `position: relative;` but it does not. If we add `position: relative;` to this row in this case **DOM** element with class `codeMirrorFullScreen` which contains **circulation rules form** will be positioned relative to this row.
https://issues.folio.org/browse/UICIRC-776
Before:
After:

UICIRC-776: Cypress issue with circulation rules form

---

CHANGELOG.md
src/settings/Models/FinePolicy/FinePolicy.js
src/settings/Validation/fine-policy/fines.js

User must not be able to save form if "Overdue fine" or "Overdue recall fine" have values less than 0. `isFloatGreaterThanOrEqualToZero` validator must be added to these fields.
https://issues.folio.org/browse/UICIRC-784
before:
after:

UICIRC-784: fix the issue when some values in `overdue fine policy` could be less than 0

---

CHANGELOG.md
package.json

Adjust `configuration.all` permission set
[UICIRC-697](https://issues.folio.org/browse/UICIRC-697)

UICIRC-697: refactor psets away from backend ".all" permissions

---

CHANGELOG.md
src/settings/Models/LoanHistoryModel.test.js

Add RTL/Jest testing for `LoanHistoryModel` in `src/settings/Models`.
https://issues.folio.org/browse/UICIRC-802

UICIRC-802: Add RTL/Jest tests for `LoanHistoryModel`

---

CHANGELOG.md
src/settings/lib/RuleEditor/RulesField.test.js

Add RTL/Jest testing for `RulesField` component in `src/settings/lib/RuleEditor`.
https://issues.folio.org/browse/UICIRC-826

UICIRC-826: Add RTL/Jest testing for  component in `src/settings/lib/RuleEditor`

---

CHANGELOG.md
src/settings/Models/LostItemFeePolicy/LostItemFeePolicy.test.js

Add RTL/Jest testing for `src/settings/Models/LostItemFeePolicy` folder.
https://issues.folio.org/browse/UICIRC-799

UICIRC-799: add RTL/Jest tests for `src/settings/Models/LostItemFeePolicy` folder

---

CHANGELOG.md
src/settings/lib/RuleEditor/utils.test.js

UI tests replacement with RTL/Jest for `src/settings/lib/RuleEditor/utils.js`.
https://issues.folio.org/browse/UICIRC-828

UICIRC-828: UI tests replacement with RTL/Jest for

---

CHANGELOG.md
src/settings/lib/RuleEditor/initFoldRules.test.js

Add RTL/Jest testing for `initFoldRules` in `src/settings/lib/RuleEditor`.
https://issues.folio.org/browse/UICIRC-829

UICIRC-829: add RTL/Jest tests for `initFoldRules` in `src/settings/lib/RuleEditor`

---

CHANGELOG.md
src/settings/TitleLevelRequests/TitleLevelRequests.js
src/settings/TitleLevelRequests/TitleLevelRequests.test.js

Components are incorrectly imported directly from stripes-* packages
https://issues.folio.org/browse/UICIRC-839
We have imports "@folio/stripes-" but all of them associated with tests or '@folio/stripes-template-editor'

UICIRC-839: Components are incorrectly imported directly from stripes-* packages

---

CHANGELOG.md
src/settings/lib/RuleEditor/rules-show-hint.js
src/settings/lib/RuleEditor/rules-show-hint.test.js

Cover functions in `rules-show-hint.js` by jest tests
[UICIRC-832](https://issues.folio.org/browse/UICIRC-832)

UICIRC-832: UI tests replacement with RTL/Jest for rules-show-hint (part 1)

---

CHANGELOG.md
src/settings/LoanHistory/LoanHistoryForm.js
src/settings/LoanHistory/LoanHistoryForm.test.js

With the permission "Settings (Circ): Can view loan history", hide the Save button on the Loan history pane
https://issues.folio.org/browse/UICIRC-767
recording on folio snapshot with diku_admin login
recording on folio snapshot with other login that has permission "ui-circulation.settings.loan-history" ("Settings (Circ): Can view loan history") and not "ui-circulation.settings.edit-loan-history" ("Settings (Circ): Can edit loan history")
- Do JIRAs exist to update the impacted …

UICIRC-767: With the permission "Settings (Circ): Can view loan history", hide the Save button on the Loan history pane

---

CHANGELOG.md
src/settings/lib/RuleEditor/initRulesCMM.js
src/settings/lib/RuleEditor/initRulesCMM.test.js

Cover initRulesCMM by jest tests
[UICIRC-837](https://issues.folio.org/browse/UICIRC-837)
`initRulesCMM.js` file doesn't have a lot of modfifcations.
I just moved outside function defined in `CodeMirror.defineMode`.

UICIRC-837: UI tests replacement with RTL/Jest for initRulesCMM

---

CHANGELOG.md
src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.js
src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.test.js
src/settings/PatronNotices/PatronNoticeForm.js
src/settings/PatronNotices/PatronNoticeForm.test.js
src/settings/RequestPolicy/RequestPolicyForm.js
src/settings/RequestPolicy/RequestPolicyForm.test.js
src/settings/utils/utils.js
src/settings/utils/utils.test.js

Fix problem with validate unique name for:
- Patron notice templates
- Request policies
- Fixed due date schedules
We should not render component until all necessary data will be loaded on layer edit.
Moved validate name by id to utilities and reuse it in all places.
https://issues.folio.org/browse/UICIRC-870
https://issues.folio.org/browse/UICIRC-872
https://issues.folio.org/browse/UICIRC-873

Fix problem with validate unique name

---

package.json

Make "ui-circulation.settings.edit-staff-slips" permission not visible for users.
This permission is necessary only as a sub-permission.
In future we could make it available in the list of all visible user permissions but now we do not need it (confirmed by Julie Bickle). 
[Tiket - UICIRC-876](https://issues.folio.org/browse/UICIRC-876)
[Related PR](https://github.com/folio-org/ui-circulation/pull/973)

UICIRC-876: Permission "Can create, edit and remove staff slips" : Cannot edit Description.

---

CHANGELOG.md
package.json

- Refs https://issues.folio.org/browse/UICIRC-892.
- Dropping unneeded `react-redux` from this component.

UICIRC-892 Drop react-redux

---

CHANGELOG.md
package.json

Update folio/stripes-template-editor to 3.2.0
https://issues.folio.org/browse/UICIRC-916

UICIRC-916: Update folio/stripes-template-editor to 3.2.0

---

CHANGELOG.md
package.json

Support feesfines interface version 18.0
In /feefineactions  (https://s3.amazonaws.com/foliodocs/api/mod-feesfines/r/feefineactions.html)  createdAt field was changed from string to UUID string and added originalCreatedAt field.
These changes do not affect this module and we just need to update the interface.
https://issues.folio.org/browse/UICIRC-920
Associated with https://issues.folio.org/browse/MODFEE-315.
Could you please notify us if we miss something?

UICIRC-920: Support feesfines interface version 18.0

---

CHANGELOG.md
src/settings/FinePolicy/components/EditSections/FinesSection/FinesSection.js
src/settings/FinePolicy/components/EditSections/OverdueAboutSection/OverdueAboutSection.js
src/settings/FixedDueDateSchedule/FixedDueDateSchedule.css
src/settings/FixedDueDateSchedule/FixedDueDateScheduleDetail.js
src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.js
src/settings/FixedDueDateSchedule/components/DetailsSections/ScedulesList/SchedulesList.css
src/settings/FixedDueDateSchedule/components/EditSections/components/ScheduleCard/ScheduleCard.css
src/settings/LostItemFeePolicy/components/EditSections/LostItemFeeAboutSection/LostItemFeeAboutSection.js
src/settings/PatronNotices/components/EditSections/PatronNoticeAboutSection/PatronNoticeAboutSection.js
src/settings/PatronNotices/components/EditSections/PatronNoticeEmailSection/PatronNoticeEmailSection.js
src/settings/StaffSlips/components/EditSections/StaffSlipAboutSection/StaffSlipAboutSection.js
src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.js

Fields use full screen width
https://issues.folio.org/browse/UICIRC-917
Fields below should use full use screen width:
1. Staff slips (/settings/circulation/staffslips/*?layer=edit)
Description
Template content
2. Fine policies (/settings/circulation/fine-policies?layer=add)
Overdue fine policy name
Description
3. Lost item fee policy (/settings/circulation/lost-item-fee-policy?layer=add)
Lost item fee policy name
Description
4. Patron notices policy (/settings/circulation/patron-notices?layer=add)
Patron notice template name
Description
Category
Subject
Body
5. Fixed due date schedules (/settings/circulation/fixed-due-date-schedules?layer=add)
Fixed due date schedule name
Description
Date range

UICIRC-917: Fields use full screen width (part 1)

---

CHANGELOG.md
src/settings/PatronNotices/tokens.js

Make the token feeCharge.additionalInfo selectable for automated f/f charge notice templates
https://issues.folio.org/browse/UICIRC-838

UICIRC-838: Make the token feeCharge.additionalInfo selectable for automated f/f charge notice templates

---

CHANGELOG.md
src/settings/lib/RuleEditor/RulesEditor.js
src/settings/lib/RuleEditor/RulesEditor.test.js

Fix Circ rules editor crashes when certain special characters entered in filter box
https://issues.folio.org/browse/UICIRC-921

UICIRC-921: Fix Circ rules editor crashes when certain special characters entered in filter box

---

CHANGELOG.md
src/constants.js
src/settings/Models/RequestPolicy/RequestPolicy.js
src/settings/Models/RequestPolicy/RequestPolicy.test.js
src/settings/RequestPolicy/RequestPolicyForm.js
src/settings/RequestPolicy/RequestPolicyForm.test.js
src/settings/RequestPolicy/RequestPolicySettings.js
src/settings/RequestPolicy/RequestPolicySettings.test.js
src/settings/RequestPolicy/components/EditSections/GeneralSection/GeneralSection.js
src/settings/RequestPolicy/components/EditSections/GeneralSection/GeneralSection.test.js
src/settings/RequestPolicy/utils/normalize.js
src/settings/RequestPolicy/utils/normalize.test.js
test/jest/__mock__/stripesComponents.mock.js
translations/ui-circulation/en.json

Allowing the selection of some Service Points as optional when creating a new request policy.
A user will be able to allow all available service points to some request type or/and a user will be able to allow only some service points to some request type.
[UICIRC-963](https://issues.folio.org/browse/UICIRC-963)

UICIRC-963: Allowing Selection of Some Pickup Service Points as Optional When Creating a New Request Policy

---

CHANGELOG.md
package.json
test/jest/babel.config.js

Upgrade babel config
Pulling the babel config directly from stripes-webpack via stripes-cli, in order to guarantee the babel plugins, versions, and config are all aligned.
https://issues.folio.org/browse/UICIRC-968

UICIRC-968: Upgrade babel config

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
package.json

Update Node.js to v18 in GitHub Actions
https://issues.folio.org/browse/UICIRC-969

UICIRC-969: Update Node.js to v18 in GitHub Actions

---

CHANGELOG.md
src/settings/RequestPolicy/RequestPolicyForm.js
src/settings/RequestPolicy/RequestPolicyForm.test.js

When a user edits a request policy that already has "Allow some pickup service points" selected with chosen service point(s) and if a user updates the page he should see service point(s) that was/were initially added to the request policy. But a user could not see it due to lack of data inside "initialValues" property.
I used "location" property to find a correct request policy id.
[UICIRC-972](https://issues.folio.org/browse/UICIRC-972)

UICIRC-972: Make visible selected service points after page reloading

---

CHANGELOG.md
src/settings/RequestPolicy/RequestPolicySettings.js

When a user tries to create/edit request policy he should see only a callout with message at the bottom of the screen. An automatic alert should not be shown (see screenshots below).
[UICIRC-967](https://issues.folio.org/browse/UICIRC-967)

UICIRC-967: Get rid of automatic alert after request failure

---

CHANGELOG.md
package.json
src/settings/PatronNotices/PatronNotices.test.js
src/settings/PatronNotices/components/EditSections/PatronNoticeEmailSection/PatronNoticeEmailEditSection.test.js
src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.test.js

- Restore and fix previously deleted Jest/RTL tests
- add "regenerator-runtime" package that was previously deleted
[UICIRC-971](https://issues.folio.org/browse/UICIRC-971)

UICIRC-971: Restore previously deleted Jest/RTL tests

---

CHANGELOG.md
src/settings/FinePolicy/components/EditSections/ReminderFeesSection/ReminderFeesSection.js

https://issues.folio.org/browse/UICIRC-982
Freeze the first five selection menus for reminder fees

UICIRC-982: Freeze the first five selection menus for reminder fees

---

CHANGELOG.md
src/constants.js
translations/ui-circulation/en.json

https://issues.folio.org/browse/UICIRC-983
Add hour to the time frequency for reminder fees

UICIRC-983: Add hour to the time frequency for reminder fees

---

src/constants.js
translations/ui-circulation/en.json

https://issues.folio.org/browse/UICIRC-983
It was decided that  hours should be replaced with minutes under reminder fees section.

UICIRC-983: Rename hours to minutes in reminder fees

---

CHANGELOG.md
package.json

Also support `feesfines` interface version `19.0`
Changes was in endpoint `/accounts` that do not used in current module
This is part of `Quesnelia (R1 2024)` release
Should be merged after merging https://issues.folio.org/browse/MODFEE-337
https://issues.folio.org/browse/UICIRC-992

UICIRC-992: Also support feesfines interface version 19.0

---

CHANGELOG.md
src/constants.js

https://issues.folio.org/browse/UICIRC-995
This PR removes `None` option from notice methods under overdue fine policies.

UICIRC-995: Remove 'None' option from notice methods

---

CHANGELOG.md
package.json

Fix permission error for Settings (Circ): Can create, edit and remove overdue fine policies
View permission used as sub permission for create, edit and remove
https://issues.folio.org/browse/UICIRC-1013

UICIRC-1013: Fix permission error for Settings (Circ): Can create, edit and remove overdue fine policies

---

CHANGELOG.md
package.json

Extend "Settings (Circ): Can create, edit and remove request policies" permission to be able to see service points.
[UICIRC-1016](https://issues.folio.org/browse/UICIRC-1016)

UICIRC-1016: Error message and cannot see or edit pickup service points in "allow some pickup service points"

---

CHANGELOG.md
src/constants.js

Create and Display new Staff slip (Search slip (Hold requests))
We read the information from DB, then render data with `EntryManager`. No other changes are needed.
https://issues.folio.org/browse/UICIRC-1001

UICIRC-1001: Create and Display new Staff slip (Search slip (Hold requests))

---

package.json

Add missing permission for Create a new Circulation setting Print hold requests (Open – Not yet filled) – Printing search slips
Add permission that was missing in https://github.com/folio-org/ui-circulation/pull/1090
Changelog already updated https://github.com/folio-org/ui-circulation/blob/master/CHANGELOG.md?plain=1#L7
https://issues.folio.org/browse/UICIRC-1000

UICIRC-1000: Add missing permission for Create a new Circulation setting Print hold requests (Open – Not yet filled) – Printing search slips

---

src/settings/FinePolicy/components/EditSections/ReminderFeesSection/ReminderFeesSection.js

This is related to the work in: https://github.com/folio-org/ui-circulation/pull/1100
It has been decided to disable: `reminderFeesPolicy.clearPatronBlockWhenPaid` for now.

UICIRC-1002: Adjust reminder fee field

---

CHANGELOG.md
src/settings/RequestCancellationReasons.test.js
test/jest/__mock__/stripesCore.mock.js
test/jest/__mock__/stripesSmartComponents.mock.js

UI tests replacement with RTL/Jest for RequestCancellationReasons.js
https://issues.folio.org/browse/UICIRC-959

UICIRC-959: UI tests replacement with RTL/Jest for RequestCancellationReasons.js

---

CHANGELOG.md
src/settings/PatronNotices/tokens.js
src/settings/PatronNotices/tokens.test.js
src/settings/StaffSlips/tokens.js
src/settings/StaffSlips/tokens.test.js

Add `displaySummary` token for patron notice templates and for staff slips templates.
[UICIRC-1059](https://folio-org.atlassian.net/browse/UICIRC-1059)

UICIRC-1059: Add displaySummary token for email templates

---

CHANGELOG.md
src/settings/FinePolicy/FinePolicyForm.js
src/settings/FinePolicy/FinePolicyForm.test.js
src/settings/LoanPolicy/LoanPolicyForm.js
src/settings/LoanPolicy/LoanPolicyForm.test.js
src/settings/LostItemFeePolicy/LostItemFeePolicyForm.js
src/settings/LostItemFeePolicy/LostItemFeePolicyForm.test.js
src/settings/NoticePolicy/NoticePolicyForm.js
src/settings/NoticePolicy/NoticePolicyForm.test.js
src/settings/PatronNotices/PatronNoticeForm.js
src/settings/PatronNotices/PatronNoticeForm.test.js
src/settings/RequestPolicy/RequestPolicyForm.js
src/settings/RequestPolicy/RequestPolicyForm.test.js
src/settings/components/FooterPane/FooterPane.js

Fix that Save & close button is missing in the circulation forms
https://issues.folio.org/browse/UICIRC-1064

UICIRC-1064: Fix that Save & close button is missing in the circulation forms

---

CHANGELOG.md
package.json
src/settings/PatronNotices/components/ViewSections/PatronNoticeEmailSection/PatronNoticeEmailSection.js
src/settings/StaffSlips/components/ViewSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.js

Only certain HTML tags should be rendered when displaying staff slips
https://issues.folio.org/browse/UICIRC-1070
For resolve current problem we should use `DOMPurify.sanitize` confirmed with John
PreviewModal fixed in https://github.com/folio-org/stripes-template-editor/pull/58

UICIRC-1070: Only certain HTML tags should be rendered when displaying staff slips

---

CHANGELOG.md
src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.js
src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.test.js
src/settings/components/FooterPane/FooterPane.js
src/settings/components/FooterPane/FooterPane.test.js
translations/ui-circulation/en.json

https://folio-org.atlassian.net/browse/UICIRC-1066
We removed local `saveAndClose` label and replace it with s`tripes-components.saveAndClose`. Also all related tests updated

UICIRC-1066: Use Save & close button label stripes-component translation key

---

CHANGELOG.md
src/settings/ViewPrintDetails/ViewPrintDetails.js
src/settings/ViewPrintDetails/ViewPrintDetails.test.js

[UICIRC-1087](https://folio-org.atlassian.net/browse/UICIRC-1089) - add page title to View Print Details settings page
This PR will point to UICIRC-1087 (Create new View Print Details Settings page).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

UICIRC-1089 - add page title to View Print Details settings page

---

package.json

[UICIRC-1093](https://folio-org.atlassian.net/browse/UICIRC-1093) - Add New 'Settings (Circ): Can enable request print details' permission
This PR is to add the missing permissions.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

UICIRC-1087 - Add New 'Settings (Circ): Can enable request print details' permission (follow-up)

---

CHANGELOG.md
src/settings/StaffSlips/tokens.js

[UICIRC-1101](https://folio-org.atlassian.net/browse/UICIRC-1101) - Add staffUsername as staff slips token in Settings.
[UICIRC-1103](https://folio-org.atlassian.net/browse/UICIRC-1103) - Add request.barcodeImage as staff slips token in Settings.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

UICIRC-1101 - Add staffSlip.staffUsername and request.barcodeImage as staff slips tokens in Settings

---

CHANGELOG.md
translations/ui-circulation/en.json

[UICIRC-1106](https://folio-org.atlassian.net/browse/UICIRC-1106)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for …

UICIRC-1106 - Update warning message when disabling 'Enable view print details (Pick slips)' configuration

---

src/index.js

It's complaining about import/no-named-as-default when the import is perfectly cromulent. Community consensus seems to be just to disable it when this happens.
This gives us a clean lint, which is the baseline I want to work from.

Disable ESlint false positive

---

CHANGELOG.md
src/settings/PatronNotices/components/EditSections/PatronNoticeAboutSection/PatronNoticeAboutSection.js
src/settings/PatronNotices/components/EditSections/PatronNoticeAboutSection/PatronNoticeAboutSection.test.js
src/settings/PatronNotices/components/EditSections/PatronNoticeEmailSection/PatronNoticeEmailEditSection.test.js
src/settings/PatronNotices/components/EditSections/PatronNoticeEmailSection/PatronNoticeEmailSection.js

Get rid of unnecessary validation of "Patron notice template name" field after editing each field on the form.
[UICIRC-1191](https://folio-org.atlassian.net/browse/UICIRC-1191)

UICIRC-1191: Patron Notice form Validation fires too often, causing unnecessary requests

---

CHANGELOG.md
package.json

Add "users.collection.get" sub-permission for viewing staff-slips.
[UICIRC-1223](https://folio-org.atlassian.net/browse/UICIRC-1223)

UICIRC-1223: Modal with error appears if user has "Settings (Circulation): Can create, edit and remove staff slips" permission

---

CHANGELOG.md
package.json

Add "users.collection.get" sub-permission for viewing circulation rules.
[UICIRC-1225](https://folio-org.atlassian.net/browse/UICIRC-1225)

UICIRC-1225: Modal with error appears if user has "Settings (Circulation): View circulation rules" permission

---

CHANGELOG.md
package.json
src/settings/StaffSlips/components/EditSections/StaffSlipAboutSection/StaffSlipAboutSection.js
src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.js
src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.test.js
src/settings/StaffSlips/components/ViewSections/StaffSlipAboutSection/StaffSlipAboutSection.js
test/jest/__mock__/stripesCore.mock.js
translations/ui-circulation/en.json

When version 1.1 or higher of the `staff-slips-storage` interface is provided, display and maintain the new `isRawHtml` field; when that field is set for a staff slip, request that raw HTML is used by the template editor.

[UICIRC-1226] Support `isRawHtml` field in staff slips

---

CHANGELOG.md
package.json

Requesting `GET /users` fails during viewing circulation patron notice template
Add missing `users.collection.get` sub-permission for `ui-circulation.settings.notice-templates`
[UICIRC-1232](https://folio-org.atlassian.net/browse/UICIRC-1232)

UICIRC-1232: Add missing users view sub-permission to view circulation patron notice template

---

CHANGELOG.md
src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.js
src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.test.js

Invocation of `useFormState` in `StaffSlipTemplateContentSection.js`
was conditional on the existence of the `useFormState` function (which
was not present when running tests). Probably as a result of this,
switching between HTML and WYSIWYG editors for a staff slip did not
work in minified builds such as that of snapshot.
The invocation is no longer conditional, and I have provided a mock so
that the test works.

[UICIRC-1238] Unconditional hook, fixes slip-editor HTML mode

---

src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.js

This reverts commit 9455894c6bea1597ba1fdde616b87ae7d46a11d0.
We no longer need this debugging output due to progress in investigating the problems described in UICIRC-1238.

Revert "Add debugging output for isRawHtml value (#1226)"
