- settings/EntrySelector.js
- settings/LoanRules.js
This PR loads policies needed by the rules editor.
> Add policies. Fix fetching lists. Fixes UCIRC-17

- settings/LoanPolicySettings.js
> Rewire the Loan Policies editor to use <EntrySelector> from stripes-components

- settings/LoanPolicyDetail.js
- settings/LoanPolicyForm.js
- settings/LoanPolicySettings.js
This PR refactors loan polices to support a new flow in UICIRC-15 and https://drive.google.com/drive/folders/0B18Bhhmr94zaMHpzb2MtWUJuMms
> Refactor loan policy. Fixes UICIRC-15.

- package.json
- settings/FixedDueDateScheduleDetail.js
- settings/FixedDueDateScheduleForm.js
- settings/FixedDueDateScheduleManager.js
- settings/index.js
There's a function goin' on right here
Some validation to check the due date years
So bring your from-dates and your to-dates too
We gonna validate all those dates for you 
VALLLLLLLLLLLL-I-DA-TION TIME COME ON!
> add validation. Refs UICIRC-20

- settings/FixedDueDateScheduleManager.js
I spent about six million hours linting earlier this year. You'd think I would have remembered to run it before I merged #18. Alas, you would have been wrong.
> lint lint lint lint lint lint lint

- CHANGELOG.md
- package.json
Refs [STRIPES-501](https://issues.folio.org/browse/STRIPES-501).
> updating dependencies. Refs STRIPES-501

- settings/LoanPolicyForm.js
- settings/LoanPolicySettings.js
https://issues.folio.org/browse/UICIRC-43
- there should be an asterisk to indicate it's required
- Validation message should read "Please select a fixed due date schedule"
> UICIRC-43: fixed due date sched: amend msg, add asterisk

- settings/LoanPolicyForm.js
- settings/LoanPolicySettings.js
[https://issues.folio.org/browse/UICIRC-51](https://issues.folio.org/browse/UICIRC-51)
> Fix alternateFixedDueDateScheduleId. Fixes UICIRC-51

- CHANGELOG.md
- package.json
- settings/ScanCheckoutForm.js
Refs [UITEST-20](https://issues.folio.org/browse/UITEST-20).
> Provide ID for Scan-ID form for easy access by tests. Refs UITEST-20.

- CHANGELOG.md
- constants.js
- settings/LoanPolicyForm.js
[https://issues.folio.org/browse/UICIRC-53](https://issues.folio.org/browse/UICIRC-53)
> Match interval period values with the values on the server. Fixes UICIRC-53.

- CHANGELOG.md
- constants.js
- settings/LoanPolicyDetail.js
- settings/LoanPolicyForm.js
- settings/LoanPolicySettings.js
[https://issues.folio.org/browse/UICIRC-53](https://issues.folio.org/browse/UICIRC-53)
> Match periodId and profileId values with the values on the server. Fixes UICIRC-53

- CHANGELOG.md
- settings/LoanPolicyForm.js
https://issues.folio.org/browse/UICIRC-56
> Fix creating loan policy with fixed due date schedule. Fixes UICIRC-56

- CHANGELOG.md
- constants.js
https://issues.folio.org/browse/UICIRC-55
> Remove Indefinite loan profile. Fix UICIRC-55.

- CHANGELOG.md
- package.json
- settings/FixedDueDateScheduleDetail.js
- settings/FixedDueDateScheduleForm.js
- settings/ViewMetadata.js
Refs [UICIRC-57](https://issues.folio.org/browse/UICIRC-57)
> favor metadata over metaData. Refs UICIRC-57

- CHANGELOG.md
- settings/LoanPolicyDetail.js
- settings/LoanPolicySettings.js
https://issues.folio.org/browse/UICIRC-58
> Show chosen Fixed due date schedule on loan policy details. Fixes UICIRC-58

- CHANGELOG.md
- settings/LoanPolicyForm.js
https://issues.folio.org/browse/UICIRC-60
> Hide  option for loan policies with a fixed loan profile. Fixes UICIRC-60

- CHANGELOG.md
- constants.js
- settings/LoanPolicyDetail.js
- settings/LoanPolicySettings.js
https://issues.folio.org/browse/UICIRC-66
> Replace int values with string representations for renewFromOptions. Fixes UICIRC-66

- CHANGELOG.md
- settings/LoanPolicyDetail.js
https://issues.folio.org/browse/UICIRC-65
> Loan policy intervals should display on read only view. Fixes UICIRC-65

- settings/FixedDueDateSchedule.css
- settings/FixedDueDateScheduleDetail.js
- settings/FixedDueDateScheduleForm.js
- settings/FixedDueDateScheduleManager.js
- translations/en.json
https://issues.folio.org/browse/UICHKOUT-426
> UICHKOUT-426: validate for overlapping date ranges

- CHANGELOG.md
- settings/LoanPolicyDetail.js
- settings/LoanPolicyForm.js
- translations/ui-circulation/en.json
https://issues.folio.org/browse/UICIRC-63
> Add last updated record metadata to loan policy form. Fixes UICIRC-63.

- package.json
https://issues.folio.org/browse/STCOR-231
> Add queryResource to stripes config. Part of STCOR-231

- package.json
- settings/StaffSlips/PreviewModal.js
- settings/StaffSlips/StaffSlipEditor.js
https://issues.folio.org/browse/UICIRC-52
> Add ability to print from a preview modal. Part of UICIRC-52

- settings/StaffSlips/StaffSlipDetail.js
- translations/ui-circulation/en.json
https://issues.folio.org/browse/UICIRC-52
> Add active field to details page. Fixes UICIRC-52

- settings/CheckoutSettingsForm.js
move validation message below checkboxes
> FOLIO-1279_update-validation-messaging

- settings/StaffSlips/PreviewModal.js
- settings/StaffSlips/StaffSlipDetail.css
- settings/StaffSlips/StaffSlipDetail.js
- settings/StaffSlips/StaffSlipEditor.js
- pass readOnly prop to disable editing
- Use StaffSlipEditor component to render the editor with tokens and without the html
- Display preview modal on clicking the preview button
> disable toolbar in view mode for staffslips

- package.json
- settings/CheckoutSettingsForm.js
- settings/FixedDueDateScheduleDetail.js
- settings/FixedDueDateScheduleForm.js
- settings/StaffSlips/StaffSlipForm.js
- settings/index.js
- settings/lib/RuleEditor/LoanRulesCMM.js
- settings/lib/RuleEditor/LoanRulesField.js
- settings/lib/RuleEditor/LoanRulesForm.js
- settings/lib/RuleEditor/fold-rules.js
- settings/lib/RuleEditor/loan-rules-show-hint.js
- settings/lib/RuleEditor/loanRules-hint.js
- test/ui-testing/settings.js
- test/ui-testing/test.js
Removes unnecessary `babel` packages and updates to the latest `eslint-config-stripes`.
>  Clean up dependencies

- CHANGELOG.md
- package.json
- settings/CheckoutSettings.js
- settings/CheckoutSettingsForm.js
- settings/FixedDueDateScheduleDetail.js
- settings/FixedDueDateScheduleForm.js
- settings/FixedDueDateScheduleManager.js
- settings/LoanPolicyDetail.js
- settings/LoanPolicyForm.js
- settings/LoanPolicySettings.js
- settings/LoanRules.js
- settings/RequestCancellationReasons.js
- settings/StaffSlips/PreviewModal.js
- settings/StaffSlips/StaffSlipDetail.js
- settings/StaffSlips/StaffSlipEditor.css
- settings/StaffSlips/StaffSlipEditor.js
- settings/StaffSlips/StaffSlipForm.js
- settings/StaffSlips/StaffSlipManager.js
- settings/index.js
- settings/lib/RuleEditor/LoanRulesForm.js
Uses new `@folio/stripes` package.
> Use stripes 1.0

- constants.js
- settings/LoanPolicyDetail.js
- settings/LoanPolicyForm.js
[Loan Policy Editor - Context-based behavior for Closed Library Due Date Management field](https://issues.folio.org/browse/UICHKOUT-452)
> [UICHKOUT-452] added context-based behavior for loan form

- CHANGELOG.md
- settings/FixedDueDateScheduleForm.js
https://issues.folio.org/browse/UICIRC-102
> Fix invalid dates. Fixes UICIRC-102

- settings/LoanPolicyDetail.js
- settings/LoanPolicyForm.js
- settings/components/PolicyPropertySetter/PolicyPropertySetter.css
- settings/components/PolicyPropertySetter/PolicyPropertySetter.js
- settings/components/PolicyPropertySetter/index.js
- settings/components/index.js
- translations/ui-circulation/en.json
Opening Time offset fields added to Loan policy in scope of UICIRC-64
> UICIRC-64. Opening time offset field added. Components refactored.

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
> Update translation strings as of 20181128T202334

- settings/LoanPolicyForm.js
- settings/components/PolicyPropertySetter/PolicyPropertySetter.js
Some element IDs were inadvertently removed in #131
> restore missing element id attributes

- settings/lib/RuleEditor/loanRules-hint.js
Fixes the console error "React is not defined"
> import React and FormattedMessage into loanRules file

- settings/FixedDueDateScheduleForm.js
- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
https://issues.folio.org/browse/STCOM-391
Related to https://github.com/folio-org/stripes-components/pull/775
> STCOM-391 Remove plus sign from translation strings

- settings/FixedDueDateScheduleForm.js
- settings/PatronNotices/PatronNoticeForm.js
- settings/StaffSlips/StaffSlipForm.js
`times` replaced `closeX` some time ago.
> don't use deprecated icons

- .stripesclirc.js
- Jenkinsfile
- karma.conf.js
- package.json
- settings/LoanRules.js
- settings/lib/RuleEditor/LoanRulesEditor.js
- settings/lib/RuleEditor/LoanRulesForm.js
- settings/lib/RuleEditor/loanRules-hint.js
- test/bigtest/.eslintrc.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/index.js
- test/bigtest/interactors/loan-rules.js
- test/bigtest/network/boot.js
- test/bigtest/network/config.js
- test/bigtest/network/cql.js
- test/bigtest/network/index.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/network/serializers/application.js
- test/bigtest/tests/loan-rules-test.js
This PR sets up a BigTest in ui-circulation module so it can be used during testing and future development. It also includes initial interactors (and couple small tests) for rule editor which will be needed during UICIRC-164 development.
https://issues.folio.org/browse/UICIRC-164
> Setup BigTest and initial tests for rule editor. Part of UICIRC-164

- CHANGELOG.md
- package.json
- settings/LoanRules.js
- settings/lib/RuleEditor/CodeMirrorCustom.css
- settings/lib/RuleEditor/LoanRulesCMM.js
- settings/lib/RuleEditor/LoanRulesEditor.js
- settings/lib/RuleEditor/loan-rules-show-hint.js
- settings/lib/RuleEditor/loanRules-hint.js
- test/bigtest/interactors/loan-rules.js
- test/bigtest/tests/loan-rules-test.js
- translations/ui-circulation/en.json
https://issues.folio.org/browse/UICIRC-164
This PR extends the rules editor in order to support multiple policy types. It also refactors the existing code a bit to make the lint happy.
> Add new policy menu to rules editor. Part of UICIRC-164

- settings/LoanPolicy/components/DeleteEntry/DeleteEntry.js
- settings/LoanPolicy/utils/normalize.js
- settings/components/DeleteConfirmationModal/DeleteConfirmationModal.js
- settings/components/DeleteConfirmationModal/actions/setSubmitSucceeded.js
- fix incorrect removing behavior for loan policy form
- added one more case to loan policy form normalization related to renewFrom field
> loan-policy-remove-fix - fixed loan policy removing

- settings/LoanPolicy/LoanPolicyDetail.js
- settings/LoanPolicy/components/ViewSections/RequestManagementSection/RequestManagementSection.js
- settings/LoanPolicy/components/ViewSections/RequestManagementSection/index.js
Add ability to view loan policy request management details.
https://issues.folio.org/browse/UICIRC-186
> UICIRC-186 - added request management view section

- constants.js
- package.json
- settings/Models/NoticePolicy/LoanNotice.js
- settings/Models/NoticePolicy/LoanNoticeSendOptions.js
- settings/Models/NoticePolicy/NoticePolicy.js
- settings/Models/NoticePolicy/index.js
- settings/NoticePolicy/NoticePolicyDetail.js
- settings/NoticePolicy/NoticePolicyForm.js
- settings/NoticePolicy/NoticePolicySettings.js
- settings/NoticePolicy/components/DetailSections/LoanNoticesSection/LoanNoticesSection.js
- settings/NoticePolicy/components/DetailSections/LoanNoticesSection/components/LoanNoticeCard/LoanNoticeCard.css
- settings/NoticePolicy/components/DetailSections/LoanNoticesSection/components/LoanNoticeCard/LoanNoticeCard.js
- settings/NoticePolicy/components/DetailSections/LoanNoticesSection/components/LoanNoticeCard/index.js
- settings/NoticePolicy/components/DetailSections/LoanNoticesSection/components/index.js
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/LoanNoticesSection.js
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/components/LoanNoticeCard/LoanNoticeCard.css
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/components/LoanNoticeCard/LoanNoticeCard.js
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/components/LoanNoticeCard/index.js
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/components/LoanNoticesList/LoanNoticesList.css
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/components/LoanNoticesList/LoanNoticesList.js
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/components/LoanNoticesList/index.js
- settings/NoticePolicy/components/EditSections/LoanNoticesSection/components/index.js
- settings/NoticePolicy/utils/get-templates.js
- settings/NoticePolicy/utils/normalize.js
- settings/Validation/notice-policy/loan-notices.js
- settings/Validation/notice-policy/notice-policy.js
- translations/ui-circulation/en.json
To add ability to create loan notices for notice policy.
https://issues.folio.org/browse/UICIRC-106
> UICIRC-106 - Single patron notice within a policy

- settings/LoanPolicy/LoanPolicyDetail.js
- settings/LoanPolicy/LoanPolicyForm.js
- settings/LoanPolicy/components/EditSections/RequestManagementSection/RequestManagementSection.js
- settings/LoanPolicy/components/ViewSections/RequestManagementSection/RequestManagementSection.js
- settings/Models/LoanPolicy/RequestManagement.js
- settings/Models/LoanPolicy/utils/defaults.js
- settings/Validation/loan-policy/request-management.js
- translations/ui-circulation/en.json
To remove pages section from edit and view mode for loan policy form.
https://issues.folio.org/browse/UICIRC-188
> UICIRC-188 - removed pages section from loan policy form

- .gitignore
- CHANGELOG.md
- settings/RequestPolicy/RequestPolicyDetail.js
- settings/RequestPolicy/RequestPolicyForm.js
- settings/RequestPolicy/RequestPolicySettings.js
- settings/RequestPolicy/components/EditSections/GeneralSection/GeneralSection.js
- settings/Validation/request-policy/unique-name.js
- translations/ui-circulation/en.json
This PR is a continuation of #187 with some additional changes required by the backend.
> Connect request policy CRU with the backend. Part of UIREQ-181

- settings/RequestPolicy/RequestPolicySettings.js
- settings/RequestPolicy/components/HeaderPane/HeaderPane.js
- settings/Validation/request-policy/unique-name.js
- test/bigtest/interactors/request-policy/request-policy-form.js
- test/bigtest/network/config.js
- test/bigtest/tests/request-policy/request-policy-form-test.js
- translations/ui-circulation/en.json
The PR includes couple additional fixes based on the feedback from PO.
https://issues.folio.org/browse/UIREQ-181
> Add extra menu items. Fix Tests. Fixes UIREQ-181

- CHANGELOG.md
- package.json
- src/settings/StaffSlips/StaffSlipManager.js
- src/settings/index.js
https://issues.folio.org/browse/UICIRC-194
> Add permission set for staff slips. Fixes UICIRC-194.

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UICIRC-192
> Update circulation OKAPI interface to v7.0. Part of UICIRC-192.

- package.json
- src/settings/RequestPolicy/RequestPolicySettings.js
- src/settings/index.js
https://issues.folio.org/browse/UICIRC-163
> Setup permissions for request policies. Fixes UICIRC-163

- package.json
This PR adds missing permissions for user's metadata.
> Add missing user permissions for metadata. Part of UICRIC-163

- CHANGELOG.md
- package.json
- src/settings/index.js
https://issues.folio.org/browse/UICIRC-193
> Add permission set for other settings. Part of UICIRC-193.

- translations/ui-circulation/en_US.json
> Update translation strings as of 20190225T222207

- translations/ui-circulation/en_US.json
> Update translation strings as of 20190227T140407

- package.json
- src/settings/PatronNotices/PatronNotices.js
- src/settings/index.js
This PR adds missing permissions for notice policies and policy templates.
https://issues.folio.org/browse/UICIRC-181
https://issues.folio.org/browse/UICIRC-182
> Add permission sets for notice policies and policy sets. Part of UICIRC-181 and UICIRC-182

- package.json
- src/settings/index.js
@aditya-matukumalli this should be hopefully the last one.
> More permission fixes. Part of UICIRC-163

- src/settings/Validation/engine/handlers.js
- src/settings/Validation/engine/validators.js
- src/settings/Validation/loan-policy/loans.js
- src/settings/Validation/loan-policy/request-management.js
- translations/ui-circulation/en.json
- Deny 0 value for recall return interval duration field.
- Allow 1 value for Loan period and opening time offset fields.
https://issues.folio.org/browse/UICIRC-207
> UICIRC-207 - Loan Policy Editor - Errors with Recall Return Interval field	

- src/settings/PatronNotices/PatronNoticeDetail.js
- src/settings/PatronNotices/PatronNoticeForm.js
Change path for template subject field
https://issues.folio.org/browse/UICIRC-211
> UICIRC-211 - changed path for patron notice template subject field

- translations/ui-circulation/en_US.json
- translations/ui-circulation/it_IT.json
> Update translation strings as of 20190313T213403

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190321T130117

- src/settings/FixedDueDateScheduleForm.js
- src/settings/PatronNotices/PatronNoticeForm.js
- src/settings/PatronNotices/PatronNotices.js
- test/bigtest/interactors/fixed-due-date-schedule/fixed-due-date-schedule-form.js
- test/bigtest/interactors/patron-notice/patron-notice-form.js
- test/bigtest/tests/fixed-due-date-schedule/fixed-due-date-schedule-form-test.js
- test/bigtest/tests/patron-notice/patron-notice-form.js
- translations/ui-circulation/en.json
Ignore timezone for fixed due date schedules datepickers. 
Add default category for fdds form.
1. Add intl to FixedDueDateScheduleForm component.
2. Add default category for fdds form.
> UICIRC-223: Add localisation for date format.

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190322T150534

- translations/ui-circulation/pt_BR.json
> Update translation strings as of 20190327T174151

- translations/ui-circulation/pt_PT.json
> Update translation strings as of 20190401T154238

- CHANGELOG.md
- src/index.js
- src/settings/index.js
Fixes [UICIRC-196](https://issues.folio.org/browse/UICIRC-196)
> sort settings page entries

- src/settings/PatronNotices/PatronNoticeEditor.css
- src/settings/PatronNotices/PatronNoticeEditor.js
- src/settings/PatronNotices/PatronNoticeForm.js
- src/settings/PatronNotices/PatronNotices.js
- src/settings/Validation/engine/handlers.js
- src/settings/Validation/engine/validators.js
- src/settings/Validation/index.js
- src/settings/Validation/patron-notice-template/index.js
- src/settings/Validation/patron-notice-template/patron-notice-template.js
- test/bigtest/interactors/patron-notice/patron-notice-form.js
- test/bigtest/tests/patron-notice/patron-notice-editor-test.js
- translations/ui-circulation/en.json
To rework validation for patron notice template form
https://issues.folio.org/browse/UICIRC-232
> UICIRC-232 - added validation for text editor

- CHANGELOG.md
- src/settings/RequestPolicy/RequestPolicyForm.js
- src/settings/RequestPolicy/RequestPolicySettings.js
- src/settings/components/CannotDeleteModal/CannotDeleteModal.js
- src/settings/components/CannotDeleteModal/index.js
- src/settings/components/index.js
- test/bigtest/interactors/request-policy/request-policy-form.js
- test/bigtest/network/config.js
- test/bigtest/tests/request-policy/request-policy-delete-test.js
- translations/ui-circulation/en.json
https://issues.folio.org/browse/UICIRC-228
> Disallow deletion of request policies used in circ rules. Part of UICIRC-228

- translations/ui-circulation/es_ES.json
- translations/ui-circulation/pt_BR.json
> Update translation strings as of 20190429T154045

- translations/ui-circulation/ar.json
- translations/ui-circulation/pt_BR.json
> Update translation strings as of 20190510T131615

- src/settings/CirculationRules.js
- test/bigtest/interactors/circulation-rules.js
- test/bigtest/network/config.js
- test/bigtest/tests/circulation-rules-test.js
https://issues.folio.org/browse/UICIRC-255
> Add support for attributes with  multiple values to circ editor. Part of UICIRC-255

- test/bigtest/interactors/other-settings/checkout-form.js
- test/bigtest/network/config.js
- test/bigtest/tests/other-settings/checkout-form-test.js
https://issues.folio.org/browse/UICIRC-235
> Add tests for checkout settings. Part of UICIRC-235

- src/settings/FixedDueDateScheduleDetail.js
- test/bigtest/interactors/fixed-due-date-schedule/fixed-due-date-schedule-detail.js
- test/bigtest/interactors/fixed-due-date-schedule/fixed-due-date-schedule-form.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/fixed-due-date-schedule.js
- test/bigtest/network/models/fixed-due-date-schedule.js
- test/bigtest/network/serializers/fixed-due-date-schedule.js
- test/bigtest/tests/fixed-due-date-schedule/fixed-due-date-schedule-detail-test.js
- test/bigtest/tests/fixed-due-date-schedule/fixed-due-date-schedule-form-test.js
https://issues.folio.org/browse/UICIRC-235
> Add more tests for fdds. Part of UICIRC-235

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190517T183537

- translations/ui-circulation/ar.json
> Update translation strings as of 20190520T224011

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190523T143922

- src/settings/FixedDueDateScheduleForm.js
- translations/ui-circulation/en.json
I have deleted dateformat props, cause datepicker is using "moment" library to get dateformat as default.
> UICIRC-254: Fix date localization.

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190529T122422

- translations/ui-circulation/en.json
- update labels for request triggering events
https://issues.folio.org/browse/UICIRC-252
> UICIRC-252 - Change "recall" triggering events on request notice policies

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190606T155546

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190612T145704

- translations/ui-circulation/pt_BR.json
> Update translation strings as of 20190614T145022

- src/settings/CheckoutSettingsForm.js
- src/settings/FixedDueDateScheduleForm.js
To add margins to action buttons for forms in circulation module.
https://issues.folio.org/browse/UICIRC-96
> UICIRC-96 - Pane buttons are not placed correctly

- CHANGELOG.md
- src/constants.js
- src/settings/LoanHistory/LoanHistory.js
- src/settings/LoanHistory/LoanHistoryForm.css
- src/settings/LoanHistory/LoanHistoryForm.js
- src/settings/components/RadioButtons/RadioButtons.js
- src/settings/components/RadioButtons/index.js
- src/settings/components/index.js
- test/bigtest/interactors/loan-history/loan-history-form.js
- test/bigtest/tests/loan-history/loan-history-form-test.js
- translations/ui-circulation/en.json
Create settings in UI for users to anonymize closed loans with fees/fines
> UIORG-175: Anonymize closed loans with fees/fines

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190627T152539

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190701T195156

- CHANGELOG.md
- package.json
- src/settings/CirculationRules.js
Add data fetching on circulation rules editor loading in the scope of the [issue](https://issues.folio.org/browse/UICIRC-272) to have needed data on the next development steps of UICIRC-258
> UICIRC-272: Add location data fetching to circulation rules editor

- src/settings/StaffSlips/StaffSlipDetail.js
- src/settings/StaffSlips/TokensList/TokensList.js
- src/settings/StaffSlips/tokens.js
- test/bigtest/tests/staff-slip/staff-slip-detail-test.js
- translations/ui-circulation/en.json
To update list of tokens for staff slips
https://issues.folio.org/browse/UICIRC-189
> UICIRC-189 - Refine list of tokens available for staff slip templates

- CHANGELOG.md
- src/settings/RequestPolicy/RequestPolicyDetail.js
- test/bigtest/helpers/messageConverters.js
- test/bigtest/interactors/notice-policy/notice-policy-detail.js
- test/bigtest/interactors/request-policy/request-policy-detail.js
- test/bigtest/tests/circulation-rules-test.js
- test/bigtest/tests/fixed-due-date-schedule/fixed-due-date-schedule-form-test.js
- test/bigtest/tests/loan-policy/loan-policy-detail-test.js
- test/bigtest/tests/loan-policy/loan-policy-form-test.js
- test/bigtest/tests/notice-policy/notice-policy-detail-test.js
- test/bigtest/tests/notice-policy/notice-policy-form-test.js
- test/bigtest/tests/patron-notice/patron-notice-editor-test.js
- test/bigtest/tests/request-policy/request-policy-detail-test.js
https://issues.folio.org/browse/UICIRC-293
> Add missing tests for request policy. Part of UICIRC-293

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190807T131714

- src/constants.js
- src/settings/CirculationRules.js
- src/settings/lib/RuleEditor/.eslintrc
- src/settings/lib/RuleEditor/Rules-hint.js
- src/settings/lib/RuleEditor/RulesEditor.js
- src/settings/lib/RuleEditor/RulesField.js
- src/settings/lib/RuleEditor/RulesForm.js
- src/settings/lib/RuleEditor/initFoldRules.js
- src/settings/lib/RuleEditor/initRulesCMM.js
- src/settings/lib/RuleEditor/rules-show-hint.js
- test/bigtest/interactors/circulation-rules.js
- test/bigtest/tests/circulation-rules-test.js
There is a string "/* eslint-disable */" in the files rules-show-hint.js and RuleEditor.js so ESLint is disabled, and developers have to spend some extra time to check the code manually during development, reviewing.
It was agreed to enable ESLint for these files and provide a refactoring to make code follow the code guidelines and increase code quality.
Acceptance criteria:
The ESLint is enabled for rules-show-hint.js and RuleEditor.js (removed the string "/* eslint-disable */");
There are not ESLint warnings and errors
The code refactoring fixes only ESLint errors and warnings
There are some test coverage issues in the `ui-circulation` module so these changes shouldn't be covered on 80% because they do not make functionalities changes.
> UICIRC-310: Handle lint issues

- src/settings/lib/RuleEditor/rules-show-hint.js
Handle `mousedown` issue I introduced while refactoring circulation rules codebase.
> UICIRC-310: Handle mousedown issue

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190819T080537

- src/constants.js
- src/settings/Models/NoticePolicy/NoticeSendOptions.js
- src/settings/NoticePolicy/NoticePolicyForm.js
- src/settings/NoticePolicy/components/EditSections/GeneralSection/GeneralSection.js
- src/settings/NoticePolicy/components/EditSections/RequestNoticesSection/RequestNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/EditSections/components/NoticesList/NoticesList.js
- src/settings/components/Period/Period.css
- src/settings/components/Period/Period.js
- test/bigtest/interactors/Period.js
- test/bigtest/interactors/notice-policy/notice-policy-form.js
- test/bigtest/tests/notice-policy/notice-policy-form-test.js
- translations/ui-circulation/en.json
To add new triggering event for request notices
https://issues.folio.org/browse/UICIRC-288
> UICIRC-288 - Add "Request expiration" as triggering event option to notice policy

- src/constants.js
- src/settings/Models/NoticePolicy/NoticeSendOptions.js
- src/settings/NoticePolicy/components/EditSections/components/NoticesList/NoticesList.js
Remove "After" option for requests time based events
https://issues.folio.org/browse/UICIRC-289
> UICIRC-289 - Patron Notice Policy > Request Notices > Updates when Triggering event Hold Expiration is selected

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20190823T083240

- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/pt_PT.json
> Update translation strings as of 20190903T134424

- CHANGELOG.md
- src/settings/CirculationRules.js
- src/settings/lib/RuleEditor/CodeMirrorCustom.css
- src/settings/lib/RuleEditor/Rules-hint.js
- src/settings/lib/RuleEditor/rules-show-hint.js
- test/bigtest/interactors/circulation-rules.js
- test/bigtest/tests/circulation-rules-test.js
- translations/ui-circulation/en.json
Add a location menu to the circulation rules editor in the scope of [issue](https://issues.folio.org/browse/UICIRC-259)
> UICIRC-259: Integrate location menu to circulation rules editor

- test/bigtest/interactors/fixed-due-date-schedule/fixed-due-date-schedule-form.js
- test/bigtest/interactors/loan-policy/loan-policy-detail.js
- test/bigtest/interactors/loan-policy/loan-policy-form.js
- test/bigtest/interactors/notice-policy/notice-policy-detail.js
- test/bigtest/interactors/notice-policy/notice-policy-form.js
- test/bigtest/interactors/request-policy/request-policy-detail.js
- test/bigtest/tests/fixed-due-date-schedule/fixed-due-date-schedule-form-test.js
- test/bigtest/tests/loan-policy/loan-policy-detail-test.js
- test/bigtest/tests/loan-policy/loan-policy-form-test.js
- test/bigtest/tests/notice-policy/notice-policy-detail-test.js
- test/bigtest/tests/notice-policy/notice-policy-form-test.js
- test/bigtest/tests/request-policy/request-policy-detail-test.js
Fix tests broken by updates in stripes-components
> Fix accordion tests

- src/settings/PatronNotices/PatronNoticeForm.js
- src/settings/PatronNotices/TokensList/TokensList.js
- src/settings/StaffSlips/TokensList/TokensList.js
- src/settings/components/TemplateEditor/EditorToolbar/EditorToolbar.js
- src/settings/components/TemplateEditor/TemplateEditor.js
- src/settings/components/TemplateEditor/TokensModal/TokensModal.js
- src/settings/components/TemplateEditor/TokensModal/store/actionTypes.js
- src/settings/components/TemplateEditor/TokensModal/store/index.js
- src/settings/components/TemplateEditor/TokensModal/store/reducer.js
- src/settings/components/TemplateEditor/TokensSection/TokensSection.js
- src/settings/utils/template-resolver.js
- test/bigtest/interactors/patron-notice/patron-notice-form.js
- test/bigtest/tests/patron-notice/patron-notice-editor-test.js
- translations/ui-circulation/en.json
Add ability use loops for tokens in template editor.
https://issues.folio.org/browse/UICIRC-304
> UICIRC-304 - Change "Edit patron notice template page" to support multiple-item templates

- src/settings/PatronNotices/TokensList/TokensList.js
- src/settings/PatronNotices/tokens.js
- test/bigtest/tests/patron-notice/patron-notice-editor-test.js
- translations/ui-circulation/en.json
To add an ability use fee/fine tokens for patron notice templates
https://issues.folio.org/browse/UICIRC-286
> UICIRC-286 - Add fee/fine tokens to patron notice templates

- src/constants.js
- translations/ui-circulation/en.json
Add "Loan due date change" event for patron notice policies
https://issues.folio.org/browse/UICIRC-325
> UICIRC-325 - Add event trigger to notices for a manual due date/time change

- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/utils/normalize.js
To clean up notice policy model from unnecessary fields
https://issues.folio.org/browse/UICIRC-343
> UICIRC-343 - Patron notice policy form works incorrectly

- package.json
"location-units" version bumped to '2.0'
> UICIRC-348: Fix the impact of the API change as per MODINVSTOR-315 for ui-circulation.

- src/settings/CirculationRules.js
- src/settings/StaffSlips/tokens.js
https://issues.folio.org/browse/UICIRC-355
> UICIRC-355: Fix staff slip preview for token item.callNumberSuffix.

- CHANGELOG.md
- src/settings/CirculationRules.js
- src/settings/lib/RuleEditor/rules-show-hint.js
- test/bigtest/interactors/circulation-rules.js
- test/bigtest/tests/circulation-rules-test.js
Fix validation error message display in the circulation rules editor in the scope of the [issue](https://issues.folio.org/browse/UICIRC-377).
> UICIRC-377: Fix validation error message display in the circulation rules editor

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20191028T151017

- src/settings/CirculationRules.js
Refs https://github.com/folio-org/ui-circulation/pull/474
> Update CirculationRules render

- src/settings/LoanPolicy/components/ViewSections/RenewalsSection/RenewalsSection.js
Show only Renewable - No if loan policy is not renewable
https://issues.folio.org/browse/UICIRC-350
> UICIRC-350 - Loan policy: Renewals section not displaying in view when Renewable = N

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20191122T195518

- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/it_IT.json
> Update translation strings as of 20200203T164535

- src/settings/LoanPolicy/utils/normalize.js
- src/settings/Models/LoanPolicy/LoanPolicy.js
- src/settings/Validation/loan-policy/loans.js
- src/settings/Validation/loan-policy/renewals.js
- src/settings/Validation/loan-policy/request-management.js
- src/settings/Validation/loan-policy/utils.js
- Update validation flow for not required invalid periods.
- Clean up validation configs
https://issues.folio.org/browse/UICIRC-327
> UICIRC-327 - Loan policy: Data silently fails to save when interval is missing

- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
> Update translation strings as of 20200207T143033

- CHANGELOG.md
- src/settings/components/TemplateEditor/EditorToolbar/EditorToolbar.js
- translations/ui-circulation/en.json
Add translations for aria-label values in EditorToolbar
https://issues.folio.org/browse/UICIRC-421
> UICIRC-421 - add translations for aria-label values in EditorToolbar

- translations/ui-circulation/pt_BR.json
> Update translation strings as of 20200309T000645

- CHANGELOG.md
- src/constants.js
- src/settings/FinePolicy/FinePolicyForm.js
- src/settings/LostItemFeePolicy/LostItemFeePolicyForm.js
- src/settings/Models/NoticePolicy/NoticePolicy.js
- src/settings/Models/NoticePolicy/NoticeSendOptions.js
- src/settings/NoticePolicy/NoticePolicyDetail.js
- src/settings/NoticePolicy/NoticePolicyForm.js
- src/settings/NoticePolicy/components/DetailSections/FeeFineNoticesSection/FeeFineNoticesSection.js
- src/settings/NoticePolicy/components/DetailSections/LoanNoticesSection/LoanNoticesSection.js
- src/settings/NoticePolicy/components/DetailSections/RequestNoticesSection/RequestNoticesSection.js
- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/EditSections/FeeFineNoticesSection/FeeFineNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/LoanNoticesSection/LoanNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/RequestNoticesSection/RequestNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/EditSections/components/NoticesList/NoticesList.js
- src/settings/NoticePolicy/utils/normalize.js
- src/settings/Validation/notice-policy/fee-fine-notices.js
- src/settings/Validation/notice-policy/loan-notices.js
- src/settings/Validation/notice-policy/notice-policy.js
- src/settings/Validation/notice-policy/request-notices.js
- src/settings/Validation/notice-policy/section-config-generator.js
- translations/ui-circulation/en.json
To add an ability to create fee fine notices for patron nice policies.
https://issues.folio.org/browse/UICIRC-451
> UICIRC-451 - Overdue fee/fine notices.

- src/settings/FixedDueDateSchedule.css
- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.css
- src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.css
- src/settings/components/Period/Period.css
- src/settings/components/Period/Period.js
- src/settings/components/TemplateEditor/ControlHeader/ControlHeader.css
- src/settings/components/TemplateEditor/TokensSection/TokensSection.css
- src/settings/components/TemplateEditor/quillCustom.css
- src/settings/lib/RuleEditor/CodeMirrorCustom.css
- src/settings/lib/RuleEditor/RulesEditor.css
- src/settings/lib/RuleEditor/RulesForm.js
https://issues.folio.org/browse/UICIRC-147
> UICIRC-147 ui-circulation: Remove hardcoded font-sizes

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/ur.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200416T214343

- translations/ui-circulation/ja.json
> Update translation strings as of 20200420T134821

- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200423T142657

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/ur.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200521T142352

- translations/ui-circulation/ru.json
> Update translation strings as of 20200522T132417

- CHANGELOG.md
- src/constants.js
- src/settings/PatronNotices/TokensList/TokensList.js
- src/settings/PatronNotices/tokens.js
- src/settings/StaffSlips/TokensList/TokensList.js
- src/settings/StaffSlips/tokens.js
- src/settings/components/TemplateEditor/TokensModal/TokensModal.js
- src/settings/components/TemplateEditor/TokensSection/TokensSection.css
- src/settings/components/TemplateEditor/TokensSection/TokensSection.js
- src/settings/utils/tokens-reducer.js
- disable unavailable tokens
- change styles for tokens modal
https://issues.folio.org/browse/UICIRC-459
> UICIRC-459 - Grey out unavailable tokens on patron notice template token modal

- src/settings/NoticePolicy/utils/normalize.js
- src/settings/PatronNotices/TokensList/TokensList.js
- src/settings/PatronNotices/tokens.js
- Update tokens for patron notices
- Update realTime flag for patron notice policies
> Update tokens for patron notices and realTime flag for patron notice policies.

- translations/ui-circulation/fr_FR.json
> Update translation strings as of 20200604T202430

- translations/ui-circulation/ru.json
> Update translation strings as of 20200608T134746

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/ur.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200609T205925

- CHANGELOG.md
- src/settings/Models/FinePolicy/FinePolicy.js
- src/settings/Validation/engine/FormValidator.js
- src/settings/Validation/engine/handlers.js
- src/settings/Validation/engine/validators.js
- src/settings/Validation/fine-policy/fines.js
- test/bigtest/network/scenarios/testFinePolicy.js
- test/bigtest/tests/fine-policy/fine-policy-edit-test.js
- test/bigtest/tests/fine-policy/fine-policy-form-test.js
- translations/ui-circulation/en.json
Update validation rules and messages for following fields:
- Overdue fine
- Overdue recall fine
- Maximum overdue fine
- Maximum overdue recall fine
https://issues.folio.org/browse/UICIRC-475
https://issues.folio.org/browse/UICIRC-476
> UICIRC-475 - Able to set Overdue Fine Max to value less than Overdue Fine

- src/settings/StaffSlips/StaffSlipForm.js
- src/settings/StaffSlips/StaffSlipManager.js
- translations/ui-circulation/en.json
Migrate staff slips form to react-final-form
https://issues.folio.org/browse/UICIRC-446
> UICIRC-446 - Migrate staff slips form to react-final-form

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/ur.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200624T130324

- src/index.js
- src/settings/PatronNotices/PatronNoticeForm.js
- src/settings/PatronNotices/PatronNotices.js
- src/settings/PatronNotices/TokensList/TokensList.js
- src/settings/RequestPolicy/RequestPolicyForm.js
- src/settings/components/TemplateEditor/TemplateEditor.js
- src/settings/components/TemplateEditor/TokensModal/TokensModal.js
- test/bigtest/interactors/patron-notice/patron-notice-form.js
- test/bigtest/interactors/request-policy/request-policy-form.js
- test/bigtest/tests/patron-notice/patron-notice-validation-test.js
- test/bigtest/tests/request-policy/request-policy-validation-test.js
Migrate Patron notice template form to react-final-form
https://issues.folio.org/browse/UICIRC-439
> UICIRC-439 - Migrate Patron notice template form to react-final-form

- src/settings/Validation/engine/handlers.js
- src/settings/Validation/engine/validators.js
- src/settings/Validation/fine-policy/fines.js
- translations/ui-circulation/en.json
Remove unnecessary validation from initial story (https://issues.folio.org/browse/UICIRC-476?focusedCommentId=80856&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-80856)
https://issues.folio.org/browse/UICIRC-476
> UICIRC-476 - Fee/Fine Overdue Fine Policies: Additional validation not in original user story

- src/settings/LostItemFeePolicy/components/EditSections/LostItemFeeSection/LostItemFeeSection.js
- src/settings/Models/LostItemFeePolicy/LostItemFeePolicy.js
- src/settings/Validation/engine/handlers.js
- src/settings/Validation/engine/validators.js
- src/settings/Validation/lost-item-fee-policy/lost-item-fee.js
To fix validation for Items aged to lost after overdue field.
https://issues.folio.org/browse/UICIRC-478
> UICIRC-478 - Lost item fee policy: Additional validation not in original user story

- src/settings/LostItemFeePolicy/components/EditSections/LostItemFeeSection/LostItemFeeSection.js
- src/settings/LostItemFeePolicy/components/ViewSections/LostItemFeeSection/LostItemFeeSection.js
- translations/ui-circulation/en.json
Change translation in `Lost Item Fee Policy`
https://issues.folio.org/browse/UICIRC-485
> UICIRC-485: Change translation

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/ur.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200707T213422

- translations/ui-circulation/pt_BR.json
> Update translation strings as of 20200710T132222

- translations/ui-circulation/de.json
> Update translation strings as of 20200716T140311

- src/settings/NoticePolicy/NoticePolicyForm.js
- src/settings/NoticePolicy/NoticePolicySettings.js
- src/settings/NoticePolicy/components/EditSections/FeeFineNoticesSection/FeeFineNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/GeneralSection/GeneralSection.js
- src/settings/NoticePolicy/components/EditSections/LoanNoticesSection/LoanNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/RequestNoticesSection/RequestNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/EditSections/components/Period/Period.js
- src/settings/NoticePolicy/components/EditSections/components/Period/index.js
Migrate patron notice policy form from redux-form to react-final-form.
https://issues.folio.org/browse/UICIRC-440
> UICIRC-440 - Migrate patron notice policy form to react-final-form

- src/settings/LoanPolicy/LoanPolicyForm.js
- src/settings/LoanPolicy/LoanPolicySettings.js
- src/settings/LoanPolicy/components/EditSections/AboutSection/AboutSection.js
- src/settings/LoanPolicy/components/EditSections/LoansSection/LoansSection.js
- src/settings/LoanPolicy/components/EditSections/Period/Period.js
- src/settings/LoanPolicy/components/EditSections/Period/index.js
- src/settings/LoanPolicy/components/EditSections/RenewalsSection/RenewalsSection.js
- src/settings/LoanPolicy/components/EditSections/RequestManagementSection/RequestManagementSection.js
Move loan policy form from redux-form to react-fianl-from
https://issues.folio.org/browse/UICIRC-443
> UICIRC-443 - Migrate Loan policy form to react-final-form

- translations/ui-circulation/it_IT.json
> Update translation strings as of 20200723T031126

- src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.js
- src/settings/NoticePolicy/NoticePolicyForm.js
- src/settings/PatronNotices/PatronNoticeForm.js
- src/settings/RequestPolicy/RequestPolicyForm.js
- src/settings/lib/RuleEditor/RulesForm.js
- move circulation rules form to react-final-from
- disable onBlur validation for already updated forms
https://issues.folio.org/browse/UICIRC-448
> UICIRC-448 - Move circulation rules form to react-final-from

- translations/ui-circulation/ru.json
> Update translation strings as of 20200806T130626

- src/settings/FinePolicy/FinePolicyForm.js
- src/settings/FinePolicy/FinePolicySettings.js
- src/settings/FinePolicy/components/EditSections/OverdueAboutSection/OverdueAboutSection.js
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSection.js
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSectionColumn.js
- src/settings/FinePolicy/utils/normalize.js
Move Overdue fine policy form to react-final-form
https://issues.folio.org/browse/UICIRC-442
> UICIRC-442 - Move overdue fine policy form to react-final-form

- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/zh_CN.json
> Update translation strings as of 20200827T215834

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/ur.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200901T173106

- translations/ui-circulation/fr_FR.json
> Update translation strings as of 20200904T163521

- src/settings/Validation/loan-policy/loan-policy.js
- src/settings/Validation/loan-policy/loans.js
- src/settings/Validation/loan-policy/renewals.js
The work for https://issues.folio.org/browse/UICIRC-392 was done in: #622
but the validation was still not working correctly for no loanable items. This PR should fix it (again).
> UICIRC-392: More changes to validation

- CHANGELOG.md
- test/bigtest/tests/notice-policy/notice-policy-detail-test.js
- translations/ui-circulation/en.json
https://issues.folio.org/browse/UICIRC-504
> UICIRC-504: Localize permission names

- translations/ui-circulation/ar.json
- translations/ui-circulation/ca.json
- translations/ui-circulation/da.json
- translations/ui-circulation/de.json
- translations/ui-circulation/en_GB.json
- translations/ui-circulation/en_SE.json
- translations/ui-circulation/en_US.json
- translations/ui-circulation/es.json
- translations/ui-circulation/es_419.json
- translations/ui-circulation/es_ES.json
- translations/ui-circulation/fr.json
- translations/ui-circulation/fr_FR.json
- translations/ui-circulation/he.json
- translations/ui-circulation/hi_IN.json
- translations/ui-circulation/hu.json
- translations/ui-circulation/it_IT.json
- translations/ui-circulation/ja.json
- translations/ui-circulation/ko.json
- translations/ui-circulation/pl.json
- translations/ui-circulation/pt_BR.json
- translations/ui-circulation/pt_PT.json
- translations/ui-circulation/ru.json
- translations/ui-circulation/ur.json
- translations/ui-circulation/zh_CN.json
- translations/ui-circulation/zh_TW.json
> Update translation strings as of 20200930T202600

- CHANGELOG.md
- src/settings/Validation/engine/handlers.js
- src/settings/Validation/engine/validators.js
- src/settings/Validation/fine-policy/fines.js
- src/settings/Validation/lost-item-fee-policy/lost-item-fee.js
- translations/ui-circulation/en.json
Update validation for fine policy in order to accept float values in numeric fields
https://issues.folio.org/browse/UICIRC-514
> UICIRC-514 - Unable to enter decimal places on Overdue Fines Policy on Honeysuckle and Snapshot Dev

- CHANGELOG.md
- src/settings/lib/RuleEditor/Rules-hint.js
- translations/ui-circulation/en.json
https://issues.folio.org/browse/UICIRC-507
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help identify …
> UICIRC-507 Modifier ! (not) - preceding value entered for a criteria, means any value except

- translations/ui-circulation/en_US.json
- translations/ui-circulation/it_IT.json
> Update translation strings as of 20201110T192302

- src/settings/FinePolicy/components/EditSections/FinesSection/FinesSection.js
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSection.js
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSectionColumn.js
- src/settings/Validation/engine/handlers.js
Allow validators to work with decimal numbers.
https://issues.folio.org/browse/UICIRC-533
> UICIRC-533 - Incorrect validation blocking user from saving overdue fine policy

- src/settings/LoanPolicy/components/EditSections/AboutSection/AboutSection.js
Add auto focus for loan policy name field.
https://issues.folio.org/browse/UICIRC-322
> UICIRC-322 - added auto focus for loan policy name field

- CHANGELOG.md
- src/constants.js
- src/settings/NoticePolicy/NoticePolicyForm.js
- src/settings/NoticePolicy/components/DetailSections/FeeFineNoticesSection/FeeFineNoticesSection.js
- src/settings/NoticePolicy/components/DetailSections/RequestNoticesSection/RequestNoticesSection.js
- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.css
- src/settings/NoticePolicy/components/EditSections/FeeFineNoticesSection/FeeFineNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/LoanNoticesSection/LoanNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/RequestNoticesSection/RequestNoticesSection.js
- src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/EditSections/components/NoticesList/NoticesList.js
- src/settings/NoticePolicy/utils/normalize.js
- src/settings/NoticePolicy/utils/notice-description.js
- src/settings/Validation/notice-policy/fee-fine-notices.js
- src/settings/components/Period/Period.js
- translations/ui-circulation/en.json
Add aged to lost triggers to notice policy 
https://issues.folio.org/browse/UICIRC-515
> UICIRC-515 - Add aged to lost triggers to notice policy 

- src/constants.js
- src/settings/NoticePolicy/NoticePolicyForm.js
- src/settings/NoticePolicy/utils/get-templates.js
- src/settings/PatronNotices/tokens.js
- translations/ui-circulation/en.json
Update patron notice template settings in accordance with latest BE requirements.
https://issues.folio.org/browse/UICIRC-537
> UICIRC-537 - Changes to patron notice template settings

- CHANGELOG.md
- package.json
Move moment from a regular to a peer and dev dependencies.
https://issues.folio.org/browse/UICIRC-513
> UICIRC-513: Move moment from a regular to a peer and dev dependencies

- CHANGELOG.md
- src/settings/LostItemFeePolicy/components/ViewSections/LostItemFeeSection/LostItemFeeSection.js
Change fields order for view mode of lost item fee policy.
https://issues.folio.org/browse/UICIRC-531
> UICIRC-531 - changed fields order for lost item fee policy view mode

- .gitignore
- CHANGELOG.md
- Update the .gitignore file
https://issues.folio.org/browse/UICIRC-550
> UICIRC-550: Update the .gitignore file

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- Add pull request template
https://issues.folio.org/browse/UICIRC-551
We add the same changes that  was added in scope  https://github.com/folio-org/ui-checkin/pull/409 with only one different in file PULL_REQUEST_TEMPLATE.md we change from UICHKIN-233 to UICIRC-551
> UICIRC-551: Add pull request template

- test/bigtest/tests/notice-policy/notice-policy-detail-test.js
- test/bigtest/tests/request-policy/request-policy-form-test.js
We should have possible to merge your changes to ui-circulation.
Skip test that randomly fails for example:
https://jenkins-aws.indexdata.com/job/folio-org/job/ui-circulation/job/UICIRC-563/4/console
https://jenkins-aws.indexdata.com/job/folio-org/job/ui-circulation/job/UICIRC-563/5/console
https://issues.folio.org/browse/UICIRC-564
> UICIRC-564: Skip unstable test

- CHANGELOG.md
- src/settings/NoticePolicy/NoticePolicyDetail.js
Shown notice template name on notice policy for fees/fines notices (view mode)
AUTOMATED_FEE_FINE was spited to AUTOMATED_FEE_FINE_CHARGE, AUTOMATED_FEE_FINE_ADJUSTMENT in scope of 
https://issues.folio.org/browse/UICIRC-537 for example
https://github.com/folio-org/ui-circulation/blob/master/src/settings/NoticePolicy/NoticePolicyForm.js#L147
https://issues.folio.org/browse/UICIRC-566
- Do …
> UICIRC-566: Shown notice template name on notice policy for fees/fines notices (view mode)

- CHANGELOG.md
- karma.conf.js
Fix failed build on ui-circulation
Use karma.conf.js that consistency with other modules (https://github.com/folio-org/ui-users/blob/master/karma.conf.js)
https://issues.folio.org/browse/UICIRC-657
Tests can be started without error
> UICIRC-657: Fix failed build on ui-circulation

- CHANGELOG.md
- src/settings/FixedDueDateSchedule/components/DetailsSections/ScedulesList/SchedulesList.js
- src/settings/FixedDueDateSchedule/components/DetailsSections/ScedulesList/SchedulesList.test.js
- test/jest/__mock__/stripesComponents.mock.js
- translations/ui-circulation/en.json
Add RTL/Jest tests for component ScedulesList (DetailsSection)
Function with tests was extracted for posibility run tests separatly for each part of incoming data
https://issues.folio.org/browse/UICIRC-601
> UICIRC-601: Add RTL/Jest testing for ScedulesList component

- CHANGELOG.md
- src/settings/FinePolicy/components/EditSections/OverdueAboutSection/OverdueAboutSection.js
- src/settings/FinePolicy/components/EditSections/OverdueAboutSection/OverdueAboutSection.test.js
- test/jest/__mock__/finalFormComponents.mock.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesComponents.mock.js
Add RTL/Jest tests for component OverdueAboutSection 
https://issues.folio.org/browse/UICIRC-595
> UICIRC-595: Add RTL/Jest testing for OverdueAboutSection component

- CHANGELOG.md
- src/settings/LostItemFeePolicy/utils/normalize.js
- src/settings/LostItemFeePolicy/utils/normalize.test.js
Add RTL/Jest tests for "normalize" function
https://issues.folio.org/browse/UICIRC-628
> UICIRC-628: Add RTL/Jest testing for `normalize` function in `LostItemFeePolicy/utils`

- CHANGELOG.md
- src/settings/LoanPolicy/utils/normalize.js
- src/settings/LoanPolicy/utils/normalize.test.js
Add RTL/Jest tests for `normalize` function in `LoanPolicy\utils`.
https://issues.folio.org/browse/UICIRC-620
> UICIRC-620: add RTL/Jest testing for `normalize` function in `LoanPolicy\utils`

- CHANGELOG.md
- src/settings/FinePolicy/components/ViewSections/FinesSection/FinesSection.js
- src/settings/FinePolicy/components/ViewSections/FinesSection/FinesSection.test.js
- translations/ui-circulation/en.json
Add RTL/Jest tests for `FinesSection` component in `FinePolicy/components/ViewSections`
https://issues.folio.org/browse/UICIRC-597
> UICIRC-597: Add RTL/Jest tests for `FinesSection` component

- CHANGELOG.md
- src/settings/LoanPolicy/components/ViewSections/LoansSection/LoansSection.js
- src/settings/LoanPolicy/components/ViewSections/LoansSection/LoansSection.test.js
Add RTL/Jest tests for `LoansSection` component in `LoanPolicy/components/ViewSections`
https://issues.folio.org/browse/UICIRC-617
> UICIRC-617: Add RTL/Jest tests for `LoansSection` component

- CHANGELOG.md
- src/settings/LoanPolicy/components/ViewSections/RequestManagementSection/RequestManagementSection.js
- src/settings/LoanPolicy/components/ViewSections/RequestManagementSection/RequestManagementSection.test.js
Add RTL/Jest tests for `RequestManagementSection` component in `LoanPolicy/components/ViewSections`
https://issues.folio.org/browse/UICIRC-618
> UICIRC-618: Add RTL/Jest test for `RequestManagementSection`

- CHANGELOG.md
- package.json
You will not be able to commit the above changes until Monday, September 13, 2021 when these changes are committed in the stripes-* repos. 
Increment `stripes` to `v7`, `react` to `v17`
https://issues.folio.org/browse/UICIRC-676
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> UICIRC-676: increment stripes to v7

- CHANGELOG.md
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSection.js
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSection.test.js
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSectionColumn.js
- src/settings/FinePolicy/components/EditSections/RangeSection/OverdueFinesSectionColumn.test.js
- test/jest/__mock__/finalFormComponents.mock.js
- test/jest/__mock__/stripesComponents.mock.js
Add RTL/Jest tests for `OverdueFinesSection` and `OverdueFinesSectionColumn` components
https://issues.folio.org/browse/UICIRC-596
> UICIRC-596: Add RTL/Jest tests for `OverdueFinesSection` and `OverdueFinesSectionColumn` components

- CHANGELOG.md
- src/settings/components/Period/Period.js
- src/settings/components/Period/Period.test.js
Add RTL/Jest unit tests for folder Period
https://issues.folio.org/browse/UICIRC-655
> UICIRC-655: UI tests replacement with RTL/Jest for folder Period

- CHANGELOG.md
- src/settings/LoanPolicy/components/EditSections/RenewalsSection/RenewalsSection.js
- src/settings/LoanPolicy/components/EditSections/RenewalsSection/RenewalsSection.test.js
- test/jest/__mock__/finalFormComponents.mock.js
- test/jest/__mock__/stripesComponents.mock.js
Add RTL/Jest testing for `RenewalsSection` component in `LoanPolicy/components/EditSections`
https://issues.folio.org/browse/UICIRC-614
> UICIRC-614: Add RTL/Jest tests for `RenewalsSection` component

- CHANGELOG.md
- src/settings/StaffSlips/TokensList/TokensList.js
- src/settings/StaffSlips/TokensList/TokensList.test.js
Add RTL/Jest testing for `TokensList` component in `settings/StaffSlips/TokensList`
https://issues.folio.org/browse/UICIRC-651
> UICIRC-651: Add RTL/Jest tests for `TokensList` component

- CHANGELOG.md
- src/settings/LoanHistory/ExceptionsList.js
- src/settings/LoanHistory/ExceptionsList.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesCore.mock.js
Add RTL/Jest testing for `ExceptionsList` component in `settings/LoanHistory`
https://issues.folio.org/browse/UICIRC-605
> UICIRC-605: Add RTL/Jest tests for `ExceptionsList` component

- CHANGELOG.md
- src/settings/StaffSlips/StaffSlipForm.js
- src/settings/StaffSlips/StaffSlipForm.test.js
- test/jest/__mock__/stripesComponents.mock.js
Add RTL/Jest testing for `StaffSlipForm` component in `settings/StaffSlips`
https://issues.folio.org/browse/UICIRC-650
> UICIRC-650: Add RTL/Jest tests for `StaffSlipForm` component

- CHANGELOG.md
- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.test.js
- test/jest/__mock__/stripesComponents.mock.js
Add RTL/Jest testing for `NoticeCard` component in `settings/NoticePolicy/components/DetailSections/components/NoticeCard`
https://issues.folio.org/browse/UICIRC-635
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UICIRC-635: Add RTL/Jest test for NoticeCard component

- CHANGELOG.md
- src/settings/CirculationRules.js
- src/settings/lib/RuleEditor/RulesEditor.css
Add possible for resizing panel in circulation rules editor
https://issues.folio.org/browse/UICIRC-709
> UICIRC-709: Add possible for resizing panel in circulation rules editor

- CHANGELOG.md
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleDetail.js
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleDetail.test.js
- test/jest/__mock__/stripes.mock.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesCore.mock.js
Add RTL/Jest testing for `FixedDueDateScheduleDetail` component in `settings\FixedDueDateSchedule`.
https://issues.folio.org/browse/UICIRC-608
> UICIRC-608: Add RTL/Jest tests for `FixedDueDateScheduleDetail` component

- CHANGELOG.md
- package.json
Support okapi interfaces `circulation` `12.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).
https://issues.folio.org/browse/UICIRC-729
> UICIRC-729: also support `circulation` `12.0`

- src/settings/CheckoutSettings/CheckoutSettings.js
- src/settings/CheckoutSettings/CheckoutSettings.test.js
- src/settings/CheckoutSettings/CheckoutSettingsForm.js
- test/bigtest/network/config.js
- translations/ui-circulation/en.json
The purpose of this PR is to add the setting to circulation setting to Enable/Disable Wildcard Barcode Match and Disambiguation in Circulation Apps. 
Please see the appropriate story [UICIRC-712](https://issues.folio.org/browse/UICIRC-712)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> UICIRC-712: Add setting to enable and disable wildcard barcode lookup

- CHANGELOG.md
- src/settings/StaffSlips/StaffSlipDetail.js
- src/settings/StaffSlips/StaffSlipDetail.test.js
Add RTL/Jest testing for `StaffSlipDetail` component in `src/settings/StaffSlips`
https://issues.folio.org/browse/UICIRC-649
> UICIRC-649: Add RTL/Jest testing for 'StaffSlipDetail' component

- CHANGELOG.md
- src/settings/StaffSlips/StaffSlipDetail.js
- src/settings/StaffSlips/StaffSlipForm.js
- src/settings/StaffSlips/StaffSlipForm.test.js
- src/settings/StaffSlips/tokens.js
- src/settings/StaffSlips/tokens.test.js
Date format in preview should change depending on localization in `Staff slips`
https://issues.folio.org/browse/UICIRC-734
en-US:
en-GB:
> UICIRC-734: Date format in preview should change depending on localization in `Staff slips`

- CHANGELOG.md
- src/settings/FinePolicy/FinePolicySettings.js
- src/settings/FinePolicy/FinePolicySettings.test.js
Add RTL/Jest testing for FinePolicyDetail component in src/settings/FinePolicy
https://issues.folio.org/browse/UICIRC-593
> UICIRC-593: Add RTL/Jest testing for FinePolicyDetail component in src/settings/FinePolicy

- CHANGELOG.md
- translations/ui-circulation/en.json
The purpose of this PR is to update the label for withe wildcard lookup.
The corresponding story is: https://issues.folio.org/browse/UICIRC-754
> UICIRC-754: Remove "Requests" from list of circulation apps to enable perform wildcard lookup of items by barcode in Circulation settings

- CHANGELOG.md
Update change log after module release
https://issues.folio.org/browse/UICIRC-755
> UICIRC-755: Update change log after module release

- CHANGELOG.md
- src/settings/CheckoutSettings/CheckoutSettingsForm.js
- src/settings/CirculationRules.js
- src/settings/FinePolicy/FinePolicyForm.js
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.js
- src/settings/LoanHistory/LoanHistoryForm.js
- src/settings/LoanPolicy/LoanPolicyForm.js
- src/settings/LostItemFeePolicy/LostItemFeePolicyForm.js
- src/settings/NoticePolicy/NoticePolicyForm.js
- src/settings/PatronNotices/PatronNoticeForm.js
- src/settings/RequestPolicy/RequestPolicyForm.js
- src/settings/StaffSlips/StaffSlipForm.js
- src/settings/TitleLevelRequests/TitleLevelRequestsForm.js
Add id for Pane component.
https://issues.folio.org/browse/UICIRC-756
> UICIRC-756: Add id for Pane component

- CHANGELOG.md
- src/settings/components/AnonymizingTypeSelect/AnonymizingTypeSelectContainer.js
- src/settings/components/AnonymizingTypeSelect/AnonymizingTypeSelectContainer.test.js
We have a problem with module launch within development process.
We had some cyclic dependencies  before. This PR resolves the problem. Also fixed dependent tests.
https://issues.folio.org/browse/UICIRC-768
> UICIRC-768: Fix problem with module launch

- CHANGELOG.md
- src/settings/TitleLevelRequests/TitleLevelRequestsForm.js
- src/settings/TitleLevelRequests/TitleLevelRequestsForm.test.js
Add the possibility to select only active templates
[UICIRC-771](https://issues.folio.org/browse/UICIRC-771)
> Add the possibility to select only active templates

- CHANGELOG.md
- src/settings/LoanPolicy/components/EditSections/LoansSection/LoansSection.test.js
- src/settings/TitleLevelRequests/TitleLevelRequestsForm.js
Cover LoanSection component by RTL/jest tests
[UICIRC-613](https://issues.folio.org/browse/UICIRC-613)
100% coverage of component
> Cover LoanSection component by RTL/jest tests

- CHANGELOG.md
> update changelog after release

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UICIRC-778
> UICIRC-778: changelog update after release

- CHANGELOG.md
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.js
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.test.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesCore.mock.js
Cover FixedDueDateScheduleForm component by RTL/jest tests
[UICIRC-609](https://issues.folio.org/browse/UICIRC-609)
> Cover FixedDueDateScheduleForm component by RTL/jest tests

- CHANGELOG.md
- src/settings/PatronNotices/PatronNoticeForm.js
- src/settings/PatronNotices/PatronNoticeForm.test.js
- test/jest/helpers/utils.js
Add RTL/Jest testing for `PatronNoticeForm` component in `src/settings/PatronNotices`
https://issues.folio.org/browse/UICIRC-644
> UICIRC-644: Add RTL/Jest testing for  component in

- CHANGELOG.md
- src/settings/FinePolicy/FinePolicyForm.test.js
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.test.js
- src/settings/LoanHistory/LoanHistoryForm.test.js
- src/settings/LoanPolicy/LoanPolicyForm.test.js
- src/settings/LostItemFeePolicy/LostItemFeePolicyForm.test.js
- src/settings/NoticePolicy/NoticePolicyForm.test.js
- src/settings/PatronNotices/PatronNoticeForm.test.js
- src/settings/RequestPolicy/RequestPolicyForm.test.js
- src/settings/StaffSlips/StaffSlipForm.test.js
- src/settings/TitleLevelRequests/TitleLevelRequestsForm.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesFinalForm.mock.js
Fix tests fails
[UICIRC-816](https://issues.folio.org/browse/UICIRC-816)
> UICIRC-816: Fix failed tests

- CHANGELOG.md
- src/constants/Validation/general.js
- src/settings/Validation/fine-policy/about.js
- src/settings/Validation/fine-policy/fines.js
- src/settings/Validation/fixed-due-date-schedule/fixed-due-date-schedule.js
- src/settings/Validation/loan-policy/about.js
- src/settings/Validation/loan-policy/loan-policy.js
- src/settings/Validation/lost-item-fee-policy/lost-item-fee.js
- src/settings/Validation/notice-policy/general.js
- src/settings/Validation/notice-policy/notice-policy.js
- src/settings/Validation/patron-notice-template/patron-notice-template.js
- src/settings/Validation/request-policy/request-policy.js
Extract repeatable part of code from `Validation`.
I checked validation for all name fields after changes - everything works fine.
https://issues.folio.org/browse/UICIRC-804
> UICIRC-804: extract repeatable part of code from `Validation`

- CHANGELOG.md
- src/constants/Validation/fine-policy.js
- src/constants/Validation/general.js
- src/settings/Validation/fine-policy/fine-policy.js
- src/settings/Validation/fine-policy/fine-policy.test.js
- src/settings/Validation/fine-policy/fines.js
- src/settings/Validation/fine-policy/fines.test.js
Add RTL/Jest testing for `src\settings\Validation\fine-policy` folder.
As this PR have some code refactoring, I retested validation of `Overdue fine policies` locally - works as expected.
https://issues.folio.org/browse/UICIRC-806
> UICIRC-806: Add RTL/Jest testing for `src\settings\Validation\fine-policy` folder

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.test.js
Update NodeJS to v16 in GitHub Actions
https://issues.folio.org/browse/UICIRC-815
Task was created for investigate problem in test https://issues.folio.org/browse/UICIRC-817
> UICIRC-815: Update NodeJS to v16 in GitHub Actions

- CHANGELOG.md
- src/settings/Models/common/ChargeAmount.test.js
- src/settings/Models/common/LostItem.test.js
- src/settings/Models/common/Metadata.test.js
- src/settings/Models/common/OverdueFine.test.js
- src/settings/Models/common/Period.test.js
- test/jest/helpers/utils.js
Add RTL/Jest testing for `src/settings/Models/common` folder.
https://issues.folio.org/browse/UICIRC-795
> UICIRC-795: Add RTL/Jest tests for `src/settings/Models/common` folder

- CHANGELOG.md
- src/settings/Models/FinePolicy/FinePolicy.js
- src/settings/Models/FinePolicy/FinePolicy.test.js
- src/settings/Models/FinePolicy/utils/helper.test.js
Cover `FinePolicy` folder in `Models`  by RTL/jest tests
[UICIRC-796](https://issues.folio.org/browse/UICIRC-796)
> UICIRC-796: UI tests replacement with RTL/Jest for `FinePolicy` folder in `Models` 

- CHANGELOG.md
- src/settings/Models/FixedDueDateSchedule/FixedDueDateSchedule.test.js
- src/settings/Models/FixedDueDateSchedule/Schedule.test.js
- test/jest/helpers/utils.js
Add RTL/Jest testing for `src/settings/Models/FixedDueDateSchedule` folder.
https://issues.folio.org/browse/UICIRC-797
> UICIRC-797: Add RTL/Jest tests for `src/settings/Models/FixedDueDateSchedule` folder

- CHANGELOG.md
- src/settings/FixedDueDateSchedule/FixedDueDateScheduleForm.test.js
Fix problem in `FixedDueDateScheduleForm` tests.
https://issues.folio.org/browse/UICIRC-817
> UICIRC-817: Fix problem in FixedDueDateScheduleForm tests

- CHANGELOG.md
- src/settings/Validation/checkout-settings/checkout-settings.js
- src/settings/Validation/checkout-settings/checkout-settings.test.js
- src/settings/Validation/checkout-settings/patron-identifiers.test.js
Add RTL/Jest testing for `src/settings/Validation/checkout-settings` folder.
https://issues.folio.org/browse/UICIRC-805
> UICIRC-805: add Jest/RTL tests for components in `src/settings/Validation/checkout-settings` folder

- CHANGELOG.md
- src/settings/lib/RuleEditor/RulesForm.js
- src/settings/lib/RuleEditor/RulesForm.test.js
Add RTL/Jest testing for `RulesForm` component in `src/settings/lib/RuleEditor`.
https://issues.folio.org/browse/UICIRC-825
> UICIRC-825: Add RTL/Jest testing for  component in

- CHANGELOG.md
- src/settings/Validation/loan-history/general.test.js
- src/settings/Validation/loan-history/loan-exceptions.test.js
- src/settings/Validation/loan-history/loan-history.test.js
Add RTL/Jest testing for `src/settings/Validation/loan-history` folder.
https://issues.folio.org/browse/UICIRC-808
> UICIRC-808: add RTL/Jest testing for `src/settings/Validation/loan-history` folder

- CHANGELOG.md
- src/settings/Validation/fixed-due-date-schedule/fixed-due-date-schedule.test.js
- src/settings/Validation/fixed-due-date-schedule/schedules.test.js
Add RTL/Jest testing for `src/settings/Validation/fixed-due-date-schedule` folder.
https://issues.folio.org/browse/UICIRC-807
> UICIRC-807: add RTL/Jest testing for `src/settings/Validation/fixed-due-date-schedule` folder

- CHANGELOG.md
- src/settings/Validation/engine/handlers.js
- src/settings/Validation/engine/handlers.test.js
UI tests replacement with RTL/Jest for `src\settings\Validation\engine\handlers.js`.
https://issues.folio.org/browse/UICIRC-814
> UICIRC-814: UI tests replacement with RTL/Jest for

- CHANGELOG.md
- src/settings/Validation/engine/FormValidator.test.js
Cover FormValidator by tests
[UICIRC-813](https://issues.folio.org/browse/UICIRC-813)
> UICIRC-813: UI tests replacement with RTL/Jest for `FormValidator.js` file in `Validation` 

- CHANGELOG.md
- src/index.js
- src/settings/LoanHistory/LoanHistorySettings.js
- src/settings/LoanHistory/LoanHistorySettings.test.js
- test/bigtest/tests/loan-history/loan-history-form-test.js
- translations/ui-circulation/en.json
Change setting "Loan history" setting to "Loan anonymization"
Issue: [UICIRC-685](https://issues.folio.org/browse/UICIRC-685)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UICIRC-685 - Change setting "Loan history" setting to "Loan anonymization"

- CHANGELOG.md
Update CHANGELOG after release
https://issues.folio.org/browse/UICIRC-875
> UICIRC-875: Update CHANGELOG after release

- CHANGELOG.md
- src/settings/PatronNotices/PatronNotices.js
- src/settings/PatronNotices/PatronNotices.test.js
Increase code coverage of "PatronNotices.js" file
[UICIRC-866](https://issues.folio.org/browse/UICIRC-866)
> UICIRC-866: UI tests replacement with RTL/Jest for `PatronNotices.js`

- CHANGELOG.md
- src/settings/Validation/notice-policy/fee-fine-notices.test.js
- src/settings/Validation/notice-policy/loan-notices.test.js
- src/settings/Validation/notice-policy/notice-policy.test.js
- src/settings/Validation/notice-policy/request-notices.test.js
- src/settings/Validation/notice-policy/section-config-generator.test.js
Cover files in notice-policy folder by unit tests
[UICIRC-811](https://issues.folio.org/browse/UICIRC-811)
> UICIRC-811: UI tests replacement with RTL/Jest for `notice-policy` folder in `Validation`

- CHANGELOG.md
- src/settings/StaffSlips/tokens.js
Add 'requester.preferredFirstName' as staff slip token in Settings
Issue: 
Added a new object to requester tokens array to reflect requester preferred name.
https://issues.folio.org/browse/UICIRC-819
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> UICIRC-819 - Add 'requester.preferredFirstName' as staff slip token in Settings

- CHANGELOG.md
- src/settings/CheckoutSettings/CheckoutSettingsForm.js
- src/settings/CheckoutSettings/CheckoutSettingsForm.test.js
- test/jest/__mock__/finalFormComponents.mock.js
- test/jest/__mock__/stripesCore.mock.js
UI tests replacement with RTL/Jest for CheckoutSettingsForm
https://issues.folio.org/browse/UICIRC-867
> UICIRC-867: UI tests replacement with RTL/Jest for CheckoutSettingsForm

- translations/ui-circulation/en.json
This PR intends to update the translation string of recently merged PR.
https://issues.folio.org/browse/UICIRC-898
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UICIRC-898 - An error for spacebar before symbols in 'Subject' field when create Patron notice template

- CHANGELOG.md
- src/settings/lib/RuleEditor/Rules-hint.js
- src/settings/lib/RuleEditor/Rules-hint.test.js
UI tests replacement with RTL/Jest for Rules-hint
https://issues.folio.org/browse/UICIRC-831
> UICIRC-831: UI tests replacement with RTL/Jest for Rules-hint

- CHANGELOG.md
- package.json
R1 2023 Orchid module release 8.0.0
https://issues.folio.org/browse/UICIRC-902
> R1 2023 Orchid module release 8.0.0

- CHANGELOG.md
- src/settings/PatronNotices/tokens.js
Add "item.loanType" as notice token in Settings
Update the tocken list for item object
https://issues.folio.org/browse/UICIRC-852
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> UICIRC-852 - Add "item.loanType" as notice token in Settings

- CHANGELOG.md
Update CHANGELOG after release
https://issues.folio.org/browse/UICIRC-919
> UICIRC-919: Update CHANGELOG after release

- CHANGELOG.md
- package.json
- src/index.js
- src/settings/lib/RuleEditor/RulesEditor.js
- src/settings/lib/RuleEditor/RulesEditor.test.js
- src/settings/lib/RuleEditor/RulesForm.js
Create a new permission that grants View-only access to Settings > Circulation > Circulation rules
1. Added a new permission to have "view only" access for circulation rules.
2. Updated existing permission "ui-circulation.settings.circulation-rules" to "ui-circulation.settings.edit-circulation-rules" to inherit view sub permissions and also have those PUT sub permissions (already existing).
3. CodeMirror(controlled) will be rendered in readOnly mode with 'nocursor' when the logged in user does not have edit permissions.
https://issues.folio.org/browse/UICIRC-843
If there are breaking changes, please …
> UICIRC-843 - Create a new permission that grants View-only access to Settings > Circulation > Circulation rules

- CHANGELOG.md
- src/settings/StaffSlips/tokens.js
Add "Departments" as staff slip token in Settings
https://issues.folio.org/browse/UICIRC-844
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> UICIRC-844 - Add 'requester.departments' as a new token for staff slips

- CHANGELOG.md
- src/settings/PatronNotices/tokens.js
Make the token feeCharge.additionalInfo selectable for automated f/f adjustment notice templates
https://issues.folio.org/browse/UICIRC-862
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UICIRC-862 - Make the token feeCharge.additionalInfo selectable for automated f/f adjustment notice templates

- CHANGELOG.md
- src/settings/Models/NoticePolicy/NoticeSendOptions.js
- src/settings/Models/NoticePolicy/NoticeSendOptions.test.js
- src/settings/NoticePolicy/NoticePolicySettings.js
- src/settings/NoticePolicy/NoticePolicySettings.test.js
- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/DetailSections/components/NoticeCard/NoticeCard.test.js
- src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.js
- src/settings/NoticePolicy/components/EditSections/components/NoticeCard/NoticeCard.test.js
- src/settings/NoticePolicy/utils/get-real-time-labels.js
- src/settings/NoticePolicy/utils/get-real-time-labels.test.js
- src/settings/NoticePolicy/utils/is-real-time-message.js
- src/settings/NoticePolicy/utils/is-real-time-message.test.js
- src/settings/NoticePolicy/utils/normalize.js
- src/settings/NoticePolicy/utils/normalize.test.js
- src/settings/NoticePolicy/utils/notice-description.js
- src/settings/NoticePolicy/utils/notice-description.test.js
- src/settings/Validation/notice-policy/section-config-generator.js
- src/settings/Validation/notice-policy/section-config-generator.test.js
- translations/ui-circulation/en.json
Add multiple options for fee/fine notices when "Lost item fee(s) charged" is selected.
[UICIRC-895](https://issues.folio.org/browse/UICIRC-895)
> UICIRC-895: Update patron notice policy: Multiples options for "Lost item fee(s) charged"

- CHANGELOG.md
- src/settings/PatronNotices/TokensList/TokensList.js
- src/settings/PatronNotices/TokensList/TokensList.test.js
Add new multiples token: Multiple fee/fine charges for the Fee/fine charge section
https://issues.folio.org/browse/UICIRC-904
Associated with https://github.com/folio-org/stripes-template-editor/pull/47
> UICIRC-904: Add new multiples token: Multiple fee/fine charges for the Fee/fine charge section

- CHANGELOG.md
- src/settings/StaffSlips/tokens.js
- src/settings/StaffSlips/tokens.test.js
Update staff slips to have the primary service point for an effective location
Added a new token for primary service point.
https://issues.folio.org/browse/CIRC-1785
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> CIRC-1785 Added new token effectiveLocationPrimaryServicePointName

- CHANGELOG.md
- package.json
Also support circulation 14.0
Field fulfilmentPreference was renamed to fulfillmentPreference. This changes do not affect current module.
https://issues.folio.org/browse/UICIRC-935
> UICIRC-935: Also support circulation 14.0

- CHANGELOG.md
- src/settings/StaffSlips/tokens.js
- src/settings/StaffSlips/tokens.test.js
Update staff slips to have the request date
add new token for request date
https://issues.folio.org/browse/CIRC-1784
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> CIRC-1784 added request.requestDate token

- CHANGELOG.md
- src/settings/lib/RuleEditor/rules-show-hint.test.js
UI tests replacement with RTL/Jest for rules-show-hint.
[UICIRC-845](https://issues.folio.org/browse/UICIRC-845)
> UICIRC-845: UI tests replacement with RTL/Jest for rules-show-hint

- src/settings/FinePolicy/FinePolicySettings.js
- src/settings/FinePolicy/FinePolicySettings.test.js
- src/settings/FinePolicy/components/EditSections/ReminderFeesSection/ReminderFeesSection.js
- src/settings/FinePolicy/components/ViewSections/ReminderFeesSection/ReminderFeesSection.js
- src/settings/Models/FinePolicy/FinePolicy.test.js
- src/settings/Models/ReminderFeesPolicy/ReminderFeesPolicy.js
- src/settings/Models/ReminderFeesPolicy/ReminderFeesPolicy.test.js
- test/jest/fixtures/reminderFeesPolicy.js
- translations/ui-circulation/en.json
https://issues.folio.org/browse/UICIRC-955
Add additional fields to the reminder fees section.
> UICIRC-955: Add additional fields to reminder fees

- src/settings/PatronNotices/tokens.js
https://issues.folio.org/browse/UICIRC-938
The work for this was done in https://github.com/folio-org/ui-circulation/pull/1040
This PR just adjusts the token names based on the feedback from PO.
> UICIRC-938: Adjust address token names

- CHANGELOG.md
- package.json
- src/settings/components/FooterPane/FooterPane.test.js
Add possible for run axe tests
https://issues.folio.org/browse/UUICIRC-965
> UICIRC-965: Add possible for run axe tests

- src/settings/PatronNotices/tokens.js
Adjust token name for address type to `user.primaryDeliveryAddressType`
https://issues.folio.org/browse/UICIRC-938
> UICIRC-938: Adjust token name

- package.json
Whoops, missed the peerdep somehow in #1069.
Refs [UICIRC-977](https://issues.folio.org/browse/UICIRC-977)
> UICIRC-977 update react-intl peer to v6

- CHANGELOG.md
- src/settings/LostItemFeePolicy/LostItemFeePolicyForm.css
- src/settings/LostItemFeePolicy/LostItemFeePolicyForm.js
Fix wrong position of Cancel and Save & close button
https://issues.folio.org/browse/UICIRC-1014
> UICIRC-1014: Fix wrong position of Cancel and Save & close button

- CHANGELOG.md
[UICIRC-1015](https://issues.folio.org/browse/UICIRC-1015)
> UICIRC-1015: Update changelog after release

- CHANGELOG.md
https://issues.folio.org/browse/UICIRC-1012
> UICIRC-1012: Update changelog after release

- CHANGELOG.md
[UICIRC-1018](https://issues.folio.org/browse/UICIRC-1018)
> UICIRC-1018: Update changelog after release

- CHANGELOG.md
- translations/ui-circulation/en.json
UICIRC-1017: Change label for count closed days.
https://issues.folio.org/browse/UICIRC-1017
> UICIRC-1017: Change label for count closed days

- CHANGELOG.md
- src/settings/FinePolicy/components/EditSections/ReminderFeesSection/ReminderFeesSection.js
Unfreeze reminder fees options
https://issues.folio.org/browse/UICIRC-1002
https://issues.folio.org/browse/UICIRC-1005
https://issues.folio.org/browse/UICIRC-1006
> UICIRC-1002: Unfreeze reminder fees options

- CHANGELOG.md
- src/settings/FinePolicy/components/EditSections/ReminderFeesSection/ReminderFeesFields.js
- src/settings/FinePolicy/components/ViewSections/ReminderFeesSection/ReminderFeesSection.js
- src/settings/FinePolicy/components/ViewSections/ReminderFeesSection/ReminderFeesSection.test.js
- src/settings/Validation/reminder-fees-policy/reminder-fees-policy.js
- src/settings/Validation/reminder-fees-policy/reminder-fees-policy.test.js
- translations/ui-circulation/en.json
https://folio-org.atlassian.net/browse/UICIRC-1046
Disable `Block template` under reminder fees.
> UICIRC-1046: Disable block template under reminder fees

- CHANGELOG.md
- src/settings/CirculationRules.js
- src/settings/CirculationRules.test.js
- test/jest/__mock__/stripesComponents.mock.js
Cover CirculationRules.js by tests
[UICIRC-958](https://folio-org.atlassian.net/browse/UICIRC-958)
> UICIRC-958: UI tests replacement with RTL/Jest for `CirculationRules.js`

- CHANGELOG.md
- package.json
- src/index.js
- src/settings/NoticePolicy/NoticePolicySettings.test.js
- src/settings/StaffSlips/StaffSlipForm.js
- src/settings/StaffSlips/StaffSlipForm.test.js
- src/settings/StaffSlips/StaffSlipManager.js
- src/settings/StaffSlips/StaffSlipManager.test.js
- src/settings/components/FooterPane/FooterPane.js
- src/settings/components/FooterPane/FooterPane.test.js
- translations/ui-circulation/en.json
Create a new permission Settings (Circulation): Can view staff slips
https://issues.folio.org/browse/UICIRC-848
> UICIRC-848: Create a new permission Settings (Circulation): Can view staff slips

- CHANGELOG.md
- package.json
Update changelog and package.json
https://issues.folio.org/browse/UICIRC-1068
> UICIRC-1068: Update changelog and package.json

- package.json
Extension of https://github.com/folio-org/ui-circulation/pull/1137
[UICIRC-1040](https://folio-org.atlassian.net/browse/UICIRC-1040)
There is no CHANGELOG.md file updates because this PR is a follow up of previous work.
> UICIRC-1040: Add new get permission for tlr settings

- CHANGELOG.md
- package.json
- src/index.js
- src/settings/CheckoutSettings/CheckoutSettingsForm.js
- src/settings/ConsortiumTLR/ConsortiumTLRForm.js
- src/settings/LoanHistory/LoanHistoryForm.js
- src/settings/PrintHoldRequests/PrintHoldRequestsForm.js
- src/settings/RequestCancellationReasons.js
- src/settings/RequestCancellationReasons.test.js
- src/settings/TLRPatronNotices/TLRPatronNoticesForm.js
- src/settings/TitleLevelRequests/TitleLevelRequestsForm.js
- translations/ui-circulation/en.json
Add view permissions for Circulation settings
https://issues.folio.org/browse/UICIRC-1056
> UICIRC-1056: Add view permissions for Circulation settings

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
Remove bigtests from github actions
https://issues.folio.org/browse/UICIRC-1079
> UICIRC-1079: Remove bigtests from github actions

- src/settings/ViewPrintDetails/ViewPrintDetails.js
- src/settings/ViewPrintDetails/hooks/usePrintDetailsSettings/usePrintDetailsSettings.js
[UICIRC-1087](https://folio-org.atlassian.net/browse/UICIRC-1087)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for …
> UICIRC-1087 - fetch 'enable print log settings' api with '(name=printEventLogFeature)' query params (follow-up)

- CHANGELOG.md
Update CHANGELOG after release
https://folio-org.atlassian.net/browse/UICIRC-1129
> UICIRC-1129: Update CHANGELOG after release

- CHANGELOG.md
- package.json
*BREAKING* Update react-intl to ^7
https://folio-org.atlassian.net/browse/UICIRC-1177
> UICIRC-1177: *BREAKING* Update react-intl to ^7

- CHANGELOG.md
- src/index.js
- src/settings/utils/utils.js
- test/jest/__mock__/stripesCore.mock.js
Make Consortium title level request settings available only in Central tenant
https://folio-org.atlassian.net/browse/UICIRC-1192
> UICIRC-1192: Make Consortium title level request settings available only in Central tenant

- src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.test.js
> Move jest.mock invocation down below imports

- src/settings/StaffSlips/components/EditSections/StaffSlipTemplateContentSection/StaffSlipTemplateContentSection.js
> Add debugging output for isRawHtml value

- CHANGELOG.md
- src/deprecated/settings/TitleLevelRequests/TitleLevelRequestsForm.js
Hide button when there are no permission for it
https://folio-org.atlassian.net/browse/UICIRC-1130
> UICIRC-1130: Hide button when there are no permission for it

- CHANGELOG.md
- src/constants.js
- src/settings/ConsortiumTLR/ConsortiumTLR.js
- src/settings/ConsortiumTLR/ConsortiumTLR.test.js
- src/settings/ConsortiumTLR/ConsortiumTLRForm.js
- src/settings/ConsortiumTLR/ConsortiumTLRForm.test.js
- src/settings/ConsortiumTLR/hooks/index.js
- src/settings/ConsortiumTLR/hooks/useCurrentTenants/index.js
- src/settings/ConsortiumTLR/hooks/useCurrentTenants/useCurrentTenants.js
- src/settings/ConsortiumTLR/hooks/useCurrentTenants/useCurrentTenants.test.js
- src/settings/utils/utils.js
- src/settings/utils/utils.test.js
- translations/ui-circulation/en.json
ECS requesting: Implement possibility to exclude tenants (Consortium tenant Setting)
https://folio-org.atlassian.net/browse/UICIRC-1270
> UICIRC-1270: ECS requesting: Implement possibility to exclude tenants (Consortium tenant Setting)
